### ISSUE TITLE
Get backend configuration lazily and individually

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#1009]
### What is the expected enhancement?
Today when an `AccountProvider` is initialized, the configuration data for all of its backends are pulled at once. Some future backends will have much larger configuration data and this would no longer be feasible. 

The API server will provide a new endpoint for the provider to pull the backend configuration individually. The new endpoint will also allow the provider to do this lazily, to make `load_account()` much faster.

**Comment by jyu00** [comment]
More info now that the server support is done:

When a user loads an account, `qiskit-ibmq-provider` today first calls the `/Network` endpoint to get a list of providers. Then for each provider, it calls `/Network/{hub}/Groups/{group}/Projects/{project}/devices/v/1` to get the configuration files for **all** backends that provider has access to.

The server now has a new endpoint 
`GET /Network/{hub}/Groups/{group}/Projects/{project}/devices/{deviceName}/fullConfiguration` that gives back the configuration for an individual backend. Since `/Network` already returns a list of backend names, we can use this new endpoint to get the backend configuration lazily instead of all at once.

**Comment by rathishcholarajan** [comment]
Copied to https://github.com/Qiskit-Partners/qiskit-ibm/issues/43
