### ISSUE TITLE
Restore integer dictionary keys dumped by RuntimeEncoder

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#1016]
### Information

- **Qiskit IBMQ Provider version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
By default `json.dumps` converts any integer dictionary keys to strings. `json.loads`, however, does not convert them back (since JSON doesn't really support integer keys). This causes the issue mentioned in #1014 - that the `resamplings` field in `QNSPSA` uses integer as keys. 

### What is the expected behavior?
We can dump and restore `QNSPSA` while preserving the integer keys.

### Suggested solutions
Instead of special casing `resamplings`, we can probably just check the type of the dictionary keys, assuming they're all the same. For now we can just check for type `int` and add more in the future if needed.

**Comment by rathishcholarajan** [comment]
Copied to https://github.com/Qiskit-Partners/qiskit-ibm/issues/42
