### ISSUE TITLE
Add way to automatically install qiskit-requirements as dependency

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibmq-provider#1021]
### What is the expected enhancement?

Add `qiskit-experiments` to an `extras` install for something like `pip install qiskit-ibmq-provider[experiments]` or just to requirements-dev.txt to make it simpler to get that installed for running these tests:

https://github.com/Qiskit/qiskit-ibmq-provider/blob/5c11f797cd0fcbb91e1acc38e9bda6b97218dff1/test/ibmq/experiment/test_experiment_data_integration.py#L43

Right now I have to remember to manually pip install `qiskit-experiments`.

**Comment by mriedem** [comment]
Note that the `experiment-integration` tests in `cron-staging` aren't running as a result:

https://github.com/Qiskit/qiskit-ibmq-provider/runs/3178330068?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3237936/127398301-6ab71838-6e16-4e8e-bbde-89c3e27526d5.png)

**Comment by mriedem** [comment]
I guess this is technically blocked on getting a released version of qiskit-experiments:

https://github.com/Qiskit/qiskit-experiments/tags

We could install from the `main` branch but that's probably not wise.

**Comment by jyu00** [comment]
> We could install from the main branch but that's probably not wise.

`qiskit-experiments` _should_ now be stable enough for the nightly test. We probably want to catch any last minute error before the release.
