### ISSUE TITLE
Use QE_DEVICE_STAGING in TestExperimentServerIntegration

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibmq-provider#1022]
### What is the expected enhancement?

The test is hard-coding to `ibmq_qasm_simulator` here:

https://github.com/Qiskit/qiskit-ibmq-provider/blob/0937e8a6c9b9150b1f809698d7931fd7c1492c9c/test/ibmq/experiment/test_experiment_server_integration.py#L43

But that might not be available to the provider being used to run those tests.

The experiments integration tests are being run setting `QE_STAGING_DEVICE=backend1` here:

https://github.com/Qiskit/qiskit-ibmq-provider/blob/0937e8a6c9b9150b1f809698d7931fd7c1492c9c/.github/workflows/cron-staging.yml#L48

So it seems we should be able to replace that hard-coding with reading from that environment variable but default to `ibmq_qasm_simulator` if not set.

**Comment by mriedem** [comment]
Apparently have the same issue here for TestExperimentDataIntegration:

https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/test/ibmq/experiment/test_experiment_data_integration.py#L57

**Comment by jyu00** [comment]
Closed by #1024
