### ISSUE TITLE
Support new API v2 job states 

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#103]
### What is the expected behavior?

Compared to the classic API, he new API can return new "states" for a job (ie. more than `COMPLETED`, `CANCELLED`, etc). As a temporary workaround while the two versions are supported, on some endpoints at the API end the states are "simplified" in order to return only classic states (since classic qiskit does not understand the new ones, and might fail ungracefully). However, we should make use of them eventually, as they provide more information.

For short term, we should:
* [ ] verify with the API team that no endpoints are returning new states (classic + websockets)
* [ ] compile a list of the new states

Longer term, we should be able to accommodate them in the `Job` class, and be able to manage their transitions accordingly. We might not be able to accommodate this change until the classic API is fully deprecated.

**Comment by jyu00** [comment]
New API endpoints were created for new job states to be queried. This will be fixed by #610
