### ISSUE TITLE
Move test_experiment_data_integration to qiskit-experiments

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#1034]
### What is the expected enhancement?
`test_experiment_data_integration` is a set of integration tests with `qiskit-experiments` and results DB. It lives in `ibmq-provider` mostly because `qiskit-experiments` doesn't have CI setup to use IBM Quantum, and also didn't depend on `ibmq-provider`. Now that it requires `ibmq-provider`, these tests are better suited in `qiskit-experiments` than in this repo.

**Comment by rathishcholarajan** [comment]
Copied to https://github.com/Qiskit-Partners/qiskit-ibm/issues/13
