### ISSUE TITLE
Add Job Submission to IQX Dashboard

### ISSUE THREAD

**Issue by Rcuz8** [Qiskit/qiskit-ibmq-provider#1037]
### What is the expected enhancement?

Currently, the IQX Dashboard supports job and device tracking, but a user must still run code (`backend.run(..)`) to actually get the jobs on the widget.

<img width="822" alt="Screen Shot 2021-08-03 at 11 33 01 AM" src="https://user-images.githubusercontent.com/9902132/128047586-1af16318-8240-4d8b-89f5-97769b32b289.png">

 It would be nice if the widget was all-inclusive and supported creation/submission of a circuit. A lot of the heavy-lifting here is done in the [circuit composer widget](https://quantum-computing.ibm.com/lab/docs/iql/composer-widget), but I'm picturing an interface where you could store named jobs that (created in that composer) and execute them on-command by pressing a button all on the IQX Dashboard widget.

Something like this:

<img width="1164" alt="Screen Shot 2021-08-03 at 12 05 15 PM" src="https://user-images.githubusercontent.com/9902132/128048817-a86b17ca-1330-4372-a78c-68709b963249.png">

**Comment by rathishcholarajan** [comment]
Issue moved to [Qiskit-Partners/qiskit-ibm #80](https://github.com/Qiskit-Partners/qiskit-ibm/issues/80) via [**ZenHub**](https://www.zenhub.com/)
