### ISSUE TITLE
Copy experiments to realize larger number of shots than max_shots

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-ibmq-provider#1046]
### What is the expected enhancement?

Some backends have `max_shots` and we currently cannot submit job with larger shots than `max_shots`.
There are similar constraint `max_experiments`, but `ManagedJob` automatically splits a job to satisfy `max_experiments`.
It would be great if `ManagedJob` can take care of larger number of shots than `max_shots` by
- copying experiments in the same job if `max_experiments` allows, or
- copying jobs to satisfy the given shots

**Comment by rathishcholarajan** [comment]
Issue moved to [Qiskit-Partners/qiskit-ibm #79](https://github.com/Qiskit-Partners/qiskit-ibm/issues/79) via [**ZenHub**](https://www.zenhub.com/)
