### ISSUE TITLE
Get Qiskit Provider by hub/group/path

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-ibmq-provider#1047]
### What is the expected enhancement?

IBM Quantum services reports hub/group/project as a path like `<hub>/<group>/<project>`, eg., `ibm-q/open/main`. To get a provider I need to request `IBMQ.get_provider(hub=<hub>, group=<group>, path=<project>)`, it would be great if I could just do `IBMQ.get_provider(uri="<hub>/<group>/<project>")`, eg., `IBMQ.get_provider(uri="ibm-q/open/main")`.

**Comment by rathishcholarajan** [comment]
Issue moved to [Qiskit-Partners/qiskit-ibm #78](https://github.com/Qiskit-Partners/qiskit-ibm/issues/78) via [**ZenHub**](https://www.zenhub.com/)
