### ISSUE TITLE
Unify handling of exceptions

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#106]
### What is the expected behavior?

In the `IBMQConnector` used for communicating with the classic API, the conventions for raising `Exceptions` grew organically - the raising of an exception that comes from an invalid HTTP response (400, etc) usually comes from [a deep `_response_good()` check]( https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/qiskit/providers/ibmq/api/utils.py#L368) and under a generic `ApiError` which partially hiddens the root cause, merging several sources of exceptions together and relying on two message strings (`usr_msg`, `dev_msg`) for interpreting the failure. As a whole, it would be nice to be able to revise the way we are using exceptions in order to take full advantage.

A different direction is being taken during the `api_v2` contributions, but it should be revised when all the pieces are in place to make sure it is consistent and unified. Some notes and ideas can be found in the different PRs and reviews (#78, #100), and the approach is based on:
* try to take advantage of the exceptions raised by the libraries (`requests`, `websockets`) or Python directly
* instead of discarding the original exception, chain it to an ibmq-specific exception via `raise from`
* use Exception sub-classes and hierarchies to model different "types" of errors, instead of relying on specific messages
* make those message informative enough for end users, in case the exception ripples up
* ... others!

Ideally we should discuss about those guidelines for exceptions, and consolidate them (and make the pertinent changes to the code).

**Comment by jyu00** [comment]
To give an example to point 3 above, `IBMQJob` raises generic `JobError` for almost all of the exceptions. It'd be nice to be able to differentiate say an exception raised during an API call, and one raised because the job failed.
