### ISSUE TITLE
Define behaviour of retrieve_job() from another backend

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#11]
### What is the expected enhancement?

As noticed by @jaygambetta , currently `IBMQBackend.retrieve(job_id)` does _not_ enforce that the `job_id` belongs to a job that has _really_ been executed in that backend - it searches for that id among all the jobs that exists in the user account. This is prone to causing some confusion, and might make the user fetch jobs from other backends inadvertently.

### Proposed solution

We should detect that situation, and the function should act accordingly, with the ultimate goal of making it easy for the users - I think the decision is mostly about how strict we want to be. It might be worth noticing that `backend.jobs()` [does enforce a hard filter by backend](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/providers/ibmq/ibmqbackend.py#L137), so I'd lean towards keeping raising a `IBMQBackendError` if the job does not belong to a backend, along with a warning so users can correct the situation (ie. by using the right backend). Any suggestions?

**Comment by delapuente** [comment]
Are you planning to warn with something like `The job XXXX does not belong to this backends but it belongs to "this other backend"`?

**Comment by diego-plan9** [comment]
That would be a nice touch, yes :+1:
