### ISSUE TITLE
changing ibm quantum email

### ISSUE THREAD

**Issue by poig** [Qiskit/qiskit-ibmq-provider#1137]
is there a possible way to change ibmq email. The [docs](https://quantum-computing.ibm.com/composer/docs/iqx/manage/account/#account-overview), saying it is editable.

**Comment by kt474** [comment]
Hi @poig! Unfortunately it is not possible to change the email associated with your IBM Quantum account

**Comment by poig** [comment]
@kt474 Thank you for the answer.
