### ISSUE TITLE
Make use of qiskit.test.providers.BackendTestCase

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#114]
### What is the expected behavior?

Counterpart to #52.

Since a number of commits ago, terra includes [some classes for helping testing backends](https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/test/providers). Ideally this provider should make use of `BackendTestCase`  for consistency - it involves changing the class the relevant test cases inherit from, and removing individual tests as necessary.

Note that due to the dynamic nature of the `Backend`s of this provider, some extra work will probably be needed in order to be able to "run the test case for each discovered backend". Some ideas and notes can be found in the work at  #68.

**Comment by jwoehr** [comment]
Wrestling with this today, tried a few tricks, don't see a way to get something like the `unittest.TestLoader` instance that's running the tests.

**Comment by jwoehr** [comment]
I've pushed that which runs the tests but doesn't feed the calling TestRunner/TestLoader to a [branch](https://github.com/jwoehr/qiskit-ibmq-provider/tree/use_BackendTestCase_114). The code in this branch anticipates #124

**Comment by jwoehr** [comment]
Still working on this, found 2 more approaches that don't work :)

**Comment by jwoehr** [comment]
I've thought of one way to deal with the problem:

Change the Makefile `test` target to run a little program that polls IBMQ for backends and writes the test cases to the directory before calling `unittest` then afterwards deletes the autogenerated test cases unless passed a switch to leave them untouched.

**Comment by diego-plan9** [comment]
Thanks for keeping digging up into this and for the updates, @jwoehr ! The latest one is also quite creative, but I fear it might introduce some implications (most notably, restrict by quite a bit the flexibility for testing "the complete suite", by making that extra autogeneration step necessary and not inside the regular python discovery mechanisms, that in turn would tie us more to `make test` than I'd like) that probably don't outweigh the benefits.

All things considered, I'd actually be happy leaning on just not making use of `BackendTestCase` for the time being and lower the priority of the issue even further - so feel free to jump to other issue that might be less problematic (and again, thanks for battling this one and the informative comments!).

**Comment by jwoehr** [comment]
Thanks for guidance, @diego-plan9, will do!

**Comment by jyu00** [comment]
Close in favor of Qiskit-Partners/qiskit-ibm#46
