### ISSUE TITLE
Outdated info on the readme?

### ISSUE THREAD

**Issue by abbycross** [Qiskit/qiskit-ibmq-provider#1150]
On the [IBM Quantum account page](https://quantum-computing.ibm.com/account), in the API token section, there is a link to [Click here for instructions](https://github.com/Qiskit/qiskit-ibmq-provider#configure-your-ibm-quantum-credentials), which goes to the readme in this repo. However, it looks like it is directing the user to an old method, using IBMQ? Is there a newer way?

**Comment by jyu00** [comment]
@abbycross Yeah that should be updated to point to both `qiskit-ibm-runtime` and `qiskit-ibm-provider`, once the latter is released.

**Comment by kt474** [comment]
@abbycross can you create an issue for this in `sw-iqx-web`? That's where the fix would be

**Comment by abbycross** [comment]
@kt474 do you mean that the Account page should no longer point to the readme in this repo?

**Comment by kt474** [comment]
> @kt474 do you mean that the Account page should no longer point to the readme in this repo?

Yes, in ~2 weeks this repo will be deprecated so the account page should point to the readme files in https://github.com/Qiskit/qiskit-ibm-provider#readme and 
https://github.com/Qiskit/qiskit-ibm-runtime#readme
