### ISSUE TITLE
Will there be a release of qiskit-ibmq-provider that unpins the Numpy dependency?

### ISSUE THREAD

**Issue by isobelhooper** [Qiskit/qiskit-ibmq-provider#1178]
I'm working on a project that uses the `qiskit` package, the latest version of which depends specifically on v0.20.2 of `qiskit-ibmq-provider`, and noticed that our project is now restricted to only use Numpy versions < 1.24.

Will there be a release of `qiskit-ibmq-provider` that includes the fix from [#1171](https://github.com/Qiskit/qiskit-ibmq-provider/pull/1171) (unpinning numpy) that `qiskit` is then updated to use?

Or is the correct approach to wait for a version of the `qiskit` package that removes `qiskit-ibmq-provider` entirely?

**Comment by mtreinish** [comment]
I think at this point there won't be another release of the `qiskit-ibmq-provider` that unpins numpy. I agree it would have been good to release without the pin; I forgot to push for this after proposing #1171. But yesterday Qiskit 0.44.0 was released that removed `qiskit-ibmq-provider` as a dependency for `qiskit` (you can see the release notes here: https://qiskit.org/documentation/release_notes.html#qiskit-0-44-0 ) and we're preparing the archive this repository now as it's not being maintained any longer.
