### ISSUE TITLE
Error when using IBMQ.load_accounts()

### ISSUE THREAD

**Issue by vbiral** [Qiskit/qiskit-ibmq-provider#122]
### Information

- **Qiskit Terra version**: 0.8.0
- **Python version**: 3.7.1
- **Operating system**: Windows 10 x64

### What is the current behavior?
After registering for the beta version of IBM Q Experience my credentials no longer loaded using the command `IBMQ.load_accounts()`

### Steps to reproduce the problem
1. Sign in the beta version of IBM Q Experience;
2. Generate a new token at the beta version;
3. Try to load the account using: `IBMQ.load_accounts()`

### What is the expected behavior?
```
>>> from qiskit import IBMQ
>>> IBMQ.load_accounts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqprovider.py", line 199, in load_accounts
    self._append_account(credentials)
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqprovider.py", line 279, in _append_account
    single_provider = IBMQSingleProvider(credentials, self)
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqsingleprovider.py", line 52, in __init__
    self._api = self._authenticate(self.credentials)
  File "C:\ProgramData\Anaconda3\envs\quantum_env\lib\site-packages\qiskit\providers\ibmq\ibmqsingleprovider.py", line 103, in _authenticate
    .format(ex)) from root_exception
ConnectionError: Couldn't connect to IBMQ server: error during login: License required. You need to accept the License from Web Platform. https://quantumexperience.ng.bluemix.net

```

### Suggested solutions
I tested the following steps before I could solve the problem:
1. Accept the license using the link provided by the error;
2. Delete the accounts registered in qiskit with the command:
`IBMQ.delete_accounts()`
3. Create a second token in the beta version of IBMQ and try to load;

But this worked:
1. I went back to the old version of IBM Q Experience and noticed that my token was as "NULL".
After generating a new token, everything worked again, using the following steps in python:

```
from qiskit import IBMQ
IBMQ.delete_accounts()
IBMQ.save_account('MY-NEW_TOKEN')
IBMQ.load_accounts()

```

**Comment by jwoehr** [comment]
**Error when using IBMQ.load_accounts()** #122 is a Qiskit documentation query.
```
from qiskit import IBMQ
IBMQ.save_account('MY_API_TOKEN', 'MY_URL')
```
These are the directions a https://qiskit.org/documentation/install.html#install-access-ibm-q-devices-label

But the typical existing free access Qiskit user never thinks about the URL.

The idea that they have to click a "Copy URL" button and explicitly choose the beta site so their authentication will match is a new concept and needs to be documented better for existing users.

The URL for IBM QE Beta can be obtained from the copy url button on https://quantum-computing.ibm.com/account

The value is set to https://api.quantum-computing.ibm.com/api/Hubs/ibm-q/Groups/open/Projects/main .

The desired result is always obtained by a full invocation of `save_account('`_mytoken_`', 'https://api.quantum-computing.ibm.com/api/Hubs/ibm-q/Groups/open/Projects/main')`

**Comment by jwoehr** [comment]
The `~/.qiskit/` directory contents may be edited directly but this is probably unwise compared with `IBMQ.save_account('MY_API_TOKEN', 'MY_URL')` since the file format is not guaranteed.

**Comment by diego-plan9** [comment]
@vbiral to corroborate both @ajavadia and @jwoehr comments - it looks indeed that what you are experience is a combination of:

1. trying to log into the _classic_ quantum experience, probably unintendendly. The message you quote on the issue description:

  ```
  ConnectionError: Couldn't connect to IBMQ server: error during login: License required. You need to accept the License from Web Platform. https://quantumexperience.ng.bluemix.net
  ```
  
  Comes directly from the API, and in this case (based on the URL), can only come directly if trying to login into the old API. As @jwoehr mentioned, if you are intending to use the new api, at the moment you need to explicitly pass the URL gathered from the accounts page (eventually the URL will default to the new one, but at the moment we are still in beta).

2.  license changes - every now and then the license text gets updated, and that implies having to log into the Quantum Experience sites and accepting it manually (ie. through the browser). Please note that in some cases the license needs to be accepted on _both_ the classic Quantum Experience and the new Quantum Experience.

Please reopen if the issue still persists, and thanks for your patience during this transition!

**Comment by big-c-note** [comment]
Hey! I was receiving the same error and passing both the API key and the URL in this manner:

```
from qiskit import IBMQ
IBMQ.save_account('MY_API_TOKEN', 'MY_URL')
```

Same error:

> ConnectionError: Couldn't connect to IBMQ server: error during login: License required. You need to accept the License from Web Platform. https://quantumexperience.ng.bluemix.net

I ended up being able to accept the old agreement before the redirect kicked in to the new experience and that got me in. At this point I'm just assuming I'm using the new API, time will tell..

**Comment by jwoehr** [comment]
@big-c-note if you encounter problems you can chat on https://qiskit.slack.com in `#general`

**Comment by peggjt** [comment]
A simple solution is to use:

`IBMQ.update_account()`

This ensure you are updating to the new IBM Q experience.

https://github.com/Qiskit/qiskit-ibmq-provider#updating-to-the-new-ibm-q-experience

**Comment by jayur** [comment]
Hello, Im getting an SSL certificate error (screen shot below). Any ideas on how to fix it appreciated. Thanks
![sslerror](https://user-images.githubusercontent.com/21326124/88491621-ec7e6700-cf58-11ea-9ed7-c2b0882ba917.png)
