### ISSUE TITLE
job.result().job_id is 'unknown' on public devices

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#141]
### Informations

- **Qiskit version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python
backend = IBMQ.get_backend('ibmqx4')
job = backend.jobs(limit=1)[0]
print(job.result().job_id)
print(job.job_id())
```
gives, for example

```
unknown
5ced78c73dc4e500781dc077
```

### Steps to reproduce the problem
Use any public device.  Premium devices work as expected.

**Comment by diego-plan9** [comment]
Labelling as `API action` as the `job_id` field is returned directly from the API - it seems to be happening both for old and new API.

**Comment by jwoehr** [comment]
Looking at this left me with an architectural question: Why don't `qiskit.providers.ibmq.job.ibmqjob.IBMQJob` and `qiskit/providers/basejob.BaseJob` have a `to_dict()` method?

**Comment by diego-plan9** [comment]
> Looking at this left me with an architectural question: Why don't qiskit.providers.ibmq.job.ibmqjob.IBMQJob and qiskit/providers/basejob.BaseJob have a to_dict() method?

Mostly because the current `Job` class currently is not really a `Model` (as in a `qiskit.validation.BaseModel`) - it is closer to a `Backend` or a `Provider` rather than a `BackendConfiguration` or a `BackendProperties`. Some tuning of this is likely to happen during #104 eventually.

**Comment by jyu00** [comment]
This is now fixed. Note that the fix only applies to jobs submitted after the patch, and old jobs would still have `unknown` `job_id` in the results.
