### ISSUE TITLE
Result backend does not report actual backend used

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#142]
### Informations

- **Qiskit version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Consider a job `job` run on the `ibmq_poughkeepsie` device:

``` python
print(job.result().backend_name)
print(job.result().backend_version)
print(job.result().header)
print(job.qobj().header)
```

gives:

```python
ibmq_poughkeepsie
1.1.1
Obj(backend_name='ibmq_poughkeepsie', backend_version='1.1.1')
QobjHeader(backend_name='ibmq_poughkeepsie', backend_version='1.1.1')
```
(I am not sure why the result needs two different `backend_name` and `backend_version`)

but then taking the resulting `Qobj` and executing it on a different backend:

```python
job2 = backend2.run(job.qobj())

print(job2.result().backend_name)
print(job2.result().backend_version)
print(job2.result().header)
print(job2.qobj().header)
```
gives

```python
INTERNAL
1.0.1
Obj(backend_name='ibmq_poughkeepsie', backend_version='1.1.1')
QobjHeader(backend_name='ibmq_poughkeepsie', backend_version='1.1.1')
```

where `INTERNAL` is a placeholder name, and different than `ibmq_poughkeepsie` .  So the result header is returning the name of the backend from the Qobj, not the device actually run.

Indeed, removing the backend info from the qobj and running on a device:

```python
print(job3.result().backend_name)
print(job3.result().backend_version)
print(job3.result().header)
print(job3.qobj().header)
```

gives

```python
ibmq_poughkeepsie
1.1.1
Obj()
QobjHeader()
```

**Comment by jyu00** [comment]
As @nonhermitian pointed out, result header is reporting the backend name from the Qobj. According to the result schema, the header is simply a pass through:
```
        "header": {
            "type": "object",
            "properties": {},
            "description": "Header passed through from the qobj with job metadata"},
```

So I don't think it's strictly a bug given the original backend name is what got passed in the Qobj job. Further more, the qobj schema says the `backend_name` in the header is what the job is meant for, not where it's executed:
```
"backend_name": {
    "description": "The backend this set of experiments was generated for. It may also be able to execute on other backends.",
```
I do agree it can be confusing for the users, but I also don't think changing the qobj header is the right solution. Avoiding using the same name for fields with different meanings is probably a better way to go (e.g. use `executed_backend_name` and `expected_backend_name` instead).

**Comment by nonhermitian** [comment]
I am more concerned that the result backend name and version are not correct.  That should match `job.backend_name()` and version.  The qobj can be whatever it wants to be.  The result should correctly say what backend it was created on.  Currently, this is not the case.

**Comment by nonhermitian** [comment]
Closing this as it is part of the schema as defined now.
