### ISSUE TITLE
'More than one backend matches the criteria

### ISSUE THREAD

**Issue by MANORANJANSWAIN92** [Qiskit/qiskit-ibmq-provider#183]
### Information

- **Qiskit IBMQ Provider version**: 0.7.2
- **Python version**:  3.6.8
- **Operating system**: linux 18.04

### What is the current behavior?

Not able to select required backend !

### Steps to reproduce the problem
>>> from qiskit import IBMQ
>>> IBMQ.load_accounts()
>>> print(IBMQ.backends())

[<IBMQSimulator('ibmq_qasm_simulator') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmqx4') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmqx2') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmq_16_melbourne') from IBMQ(ibm-q, open, main)>,
 <IBMQBackend('ibmqx4') from IBMQ()>,
 <IBMQSimulator('ibmq_qasm_simulator') from IBMQ()>,
 <IBMQBackend('ibmqx2') from IBMQ()>,
 <IBMQBackend('ibmq_16_melbourne') from IBMQ()>]

backend=IBMQ.get_backend('ibmqx4')
QiskitBackendNotFoundError                Traceback (most recent call last)
<ipython-input-19-0b65e48736d1> in <module>
----> 1 backend=IBMQ.get_backend('ibmqx4')
      2 from qiskit.tools.monitor import job_monitor
      3 shots=8192
      4 max_credits=5
      5 job_exp=execute(qc, backend=backend,shots=shots, max_credits=max_credits)

/opt/conda/lib/python3.7/site-packages/qiskit/providers/baseprovider.py in get_backend(self, name, **kwargs)
     49         backends = self.backends(name, **kwargs)
     50         if len(backends) > 1:
---> 51             raise QiskitBackendNotFoundError('More than one backend matches the criteria')
     52         elif not backends:
     53             raise QiskitBackendNotFoundError('No backend matches the criteria')

QiskitBackendNotFoundError: 'More than one backend matches the criteria'

### What is the expected behavior?
The command should select 'ibmqx4'

**Comment by diego-plan9** [comment]
@MANORANJANSWAIN92 ,

it seems you indeed have access to multiple backends with the `ibmqx4`:

```python
[...
<IBMQBackend('ibmqx4') from IBMQ(ibm-q, open, main)>,
...
<IBMQBackend('ibmqx4') from IBMQ()>,
...]
```

in such cases, you can [select the one you want to use via extra filtering](https://qiskit.org/documentation/advanced_use_of_ibm_q_devices.html), for example:
```
backend = IBMQ.get_backend('ibmqx4', hub='ibm-q', group='open')
```

On a side note, it seems that you are using the new API or mixing access to the old API and the new one - as noted in the `README`, support is still not officially completed in the current version, and some issues might be expected. We are finishing the new release that will provide full support for the new API (and will adjust some of the usage along the way) - stay tuned for a new release in the upcoming weeks!

**Comment by MANORANJANSWAIN92** [comment]
Thanks @diego-plan9 for fixing the problem.
