### ISSUE TITLE
Silence websocket DeprecationWarning in 3.7

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#191]
### What is the expected behavior?

In Python 3.7, there are a number of `DeprecationWarnings` emitted by `websockets`:

https://travis-ci.com/Qiskit/qiskit-ibmq-provider/jobs/210703306#L519
```
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/websockets/protocol.py:911: DeprecationWarning: 'with (yield from lock)' is deprecated use 'async with lock' instead
  with (yield from self._drain_lock):
```

This seems to be tracked at https://github.com/aaugustin/websockets/issues/514, but has not made it into a pip release yet. Seeing it might be misleading and convolute a bit the logs (and might reach the user), it would be nice if we could add a filter for that warning specifically that silences the warning in the right place.

**Comment by jyu00** [comment]
Closed via #230
