### ISSUE TITLE
Revise job cancelation in api v2

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#218]
### What is the expected behavior?

It seems `test_websockets_job_final_state()` can fail ungracefully during the cancel of the job:

```
(at IBMQJob.cancel())
....
        except ApiError as error:
            self._cancelled = False
>           raise JobError('Error cancelling job: %s' % error.usr_msg)
E           qiskit.providers.exceptions.JobError: 'Error cancelling job: 400 Client Error: Bad Request for url: https://XXX/Jobs/YYY/cancel?access_token=.... Job not cancelled., Error code: JOB_NOT_CANCELLED.'
```

It might simply a small issue with the design of that particular test (the job might enter a non-cancellable state by the time we try to cancel it), but we should double-check.

**Comment by jyu00** [comment]
I spoke with the api team and they said `JOB_NOT_CANCELLED` should only happen if there's an issue with the queue. @diego-plan9 do you have more information on the job that encountered this error?

**Comment by jyu00** [comment]
There's a possibility of hitting `JOB_NOT_RUNNING` though. I'll fix that part.

**Comment by diego-plan9** [comment]
Moved to `0.3.1` milestone - after #244, the tests are temporarily skipped.
