### ISSUE TITLE
Allow caching of backend properties

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#234]
### What is the expected behavior?
The transpiler makes use of the backend properties now.  Currently, each time transpile is called it makes an API call to get the backend properties.  This adds 2-3sec of time, and is now the largest overhead in transpilation.  Instead, the properties should be cached, which will give us about a 10x speedup in our transpiler for smaller circuits.

**Comment by diego-plan9** [comment]
Assigned @ajavadia for tracking purposes - as it seems to be the issue related to #224 , and tweaked a bit the issue description to reflect better the feature.

**Comment by diego-plan9** [comment]
Fixed via #224
