### ISSUE TITLE
Backend job history is lost upon upgrading to new accounts

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#248]
### Information

- **Qiskit IBMQ Provider version**: master
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
Updating to the new account causes a lost of backend job history.

### Steps to reproduce the problem
Upgrade from old API to new API

### What is the expected behavior?
My jobs should not be lost in the transition.

**Comment by diego-plan9** [comment]
The API team is looking into it, thanks!

**Comment by nonhermitian** [comment]
Closing this here as it is brought up elsewhere.
