### ISSUE TITLE
Revise test_list_jobs_statuses_foo

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#253]
### What is the expected behavior?

In #251, some asserts were removed from the `test_list_jobs_statuses_xxx` tests as they relied on the job submitting order (more info in the linked PR). It would be nice (although not blocking) to be able to reintroduce the assertions in other form (as their original intent seems spot on) eventually.

**Comment by jyu00** [comment]
Fixed by #274.
