### ISSUE TITLE
Complete deprecation of v1 provider layer

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#268]
### What is the expected behavior?

Related to #266, when the API v1 is fully deprecated, the first layer that deals with providers will contain code not used anymore: 
* [x] `ibmqprovider.py`
* [x] `ibmqsingleprovider.py`
* [x] in `ibmqfactory.py`, the `@deprecated` methods and other compatibility tweaks

This would also open up the possibility of renaming `AccountProvider` to `IBMQProvider` again, but might end up being more confusing than it should.

**Comment by jyu00** [comment]
Also need to remove docstrings related to v1 API (e.g. in `ibmqbackend`).

**Comment by diego-plan9** [comment]
Reminder to remove the mypy ignores from #302

**Comment by luisg5** [comment]
Reminder to remove backwards compatibility return type hint in IBMQFactory.enable_account (https://github.com/Qiskit/qiskit-ibmq-provider/pull/307#discussion_r313862669).

**Comment by diego-plan9** [comment]
From https://github.com/Qiskit/qiskit-ibmq-provider/pull/344#discussion_r326232559:
> The deprecated function in ibmq/utils/deprecation.py does not seem like it is used anymore. It also might be worth removing, unless there is an intended use for it?
