### ISSUE TITLE
Distinguish between `ERROR` and `TIMEOUT` states for job results.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-ibmq-provider#27]
Retrieving the results from a job can timeout without that meaning the job is failing. However, in this case, the job status will become `ERROR` which could make the user think the complete job failed.

**Comment by jwoehr** [comment]
What's the desired pattern?

**Comment by diego-plan9** [comment]
Good question! This issue is a bit dated - maybe @delapuente and @ewinston have more info, but it might be a better idea to consider it part of  #104 entirely, as the `IBMQJob` class is a bit convoluted and might benefit from a fresh look overall.

**Comment by delapuente** [comment]
I think this is outdated. Closing. If we detect it while doing the refactor in #104, we will fix it.
