### ISSUE TITLE
Attribute error when trying to get a circuit from a provider

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#280]
### Information

- **Qiskit IBMQ Provider version**: master
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
I should not be able to grab any circuits from a provider.  However, I should also get a good exception when trying to do so.  Currently I get,

`AttributeError: 'NoneType' object has no attribute 'json'`

because nothing is being returned.

### What is the expected behavior?
I would expect an exception that says that I do not have access to this feature set.

**Comment by diego-plan9** [comment]
Can you provide enough information to reproduce the problem?

**Comment by nonhermitian** [comment]
This seems to have been a temporary issue, and is now fixed.  However the code was:

```python
provider.circuits.hardware_efficient(2,[0]*6)
```
