### ISSUE TITLE
Re-enable TestProxies tests

### ISSUE THREAD

**Issue by yeralin** [Qiskit/qiskit-ibmq-provider#284]
## What is the expected behavior?
Related to #69
Currently, `test.ibmq.test_proxies.TestProxies` tests are skipped using `@skipIf` decorator
```
@skipIf(sys.version_info >= (3, 7), 'pproxy version not supported in 3.7')
```
The tests can be re-enabled if we update `pproxy` package from version `1.2.2` to `2.1.8` in `requirements-dev.txt` file.
Then, `test.ibmq.test_proxies.TestProxies` can be run under `>= 3.7` python versions.

**Comment by yeralin** [comment]
Seems like the package upgrade does not work for python==3.5 version that we support

**Comment by yeralin** [comment]
Looking for alternatives, trying `proxy.py`

**Comment by yeralin** [comment]
`proxy.py` doesn't work for our test case since it doesn't print desired access log line **until the connection is closed**

**Comment by yeralin** [comment]
There is another solution I thought of @diego-plan9 
```
pproxy==1.2.2; python_version <= '3.5'
pproxy==2.1.8; python_version > '3.5'
```
How does this look to you?

**Comment by diego-plan9** [comment]
Yes, using pip conditionals was the exploration I hinted at by the "_play a bit with pip and make it install versions intelligently_" !

We are already checking for python version in the test itself and it would be pretty isolated, so there is no worry adding the additional checking and fine-tuning of that parameter - as a matter of fact, some tweaking of the `skipping` will also be needed to account for invalid combinations of python version + pproxy version (mostly for keeping the test suite runnable even under unusual circumstances).
