### ISSUE TITLE
Add schema for rest/auth endpoints

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#289]
### What is the expected behavior?

This issue is for being able to kick off the documenting of the communication with the API effort: the endpoints at `rest/auth.py` are a good candidate, being quite restricted and simple in their scope, yet useful enough for setting the rest of the pieces in motion.

For this issue, let's:
* for each endpoint, add [`BaseSchema`](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/validation/base.py#L92) subclasses (one for the output, other for the input, if needed) that formalizes the messages. During this iteration, let's just focus on the fields the provider actually uses (ie. some endpoints will likely return more information).
* find the right place and naming convention, with the thinking that eventually will be scaled to all endpoints (probably simply `rest/schemas/auth.py` will work for the time being).
* make the pertinent changes in the internal documentation project.

**Comment by yeralin** [comment]
Reading Marshmallow docs

**Comment by diego-plan9** [comment]
Closed via #295 and others.
