### ISSUE TITLE
Revise master failures with classic API

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#292]
### What is the expected behavior?

For tracking, the latest `master` jobs have been failing for the past couple of days - it seems contained only in the classic API, with 400 generic errors when submitting a job.

**Comment by diego-plan9** [comment]
Talking with the API team, it seems the old API issues are in a lower priority bucket - @jyu00 , can you tweak the provider's travis for adding the two old API jobs to `allow_failures`, in order not to result in a "red x"  if the rest of the jobs pass?

**Comment by jyu00** [comment]
Some of the tests now hang and will prolong the Travis run. Maybe we should skip tests that use the old API for now? Or make them part of `cron` instead?

**Comment by diego-plan9** [comment]
Let's keep an eye on the situation to see if it improves a bit, as the tests for the old API still provide quite some value - if not, the alternatives you suggest seem sensible.

**Comment by diego-plan9** [comment]
Seems we finally got a green tick for 00f13c1b467d7d7b73b3dad784866d3077a9ed9e ! Closing the issue as this round of issues seem to be fixed.
