### ISSUE TITLE
Revise recent master failures

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#305]
### What is the current behavior?

During today's round of commits to `master`, a couple of items seem to have cause errors in the tests:

From https://dev.azure.com/qiskit-ci/qiskit-ibmq-provider/_build/results?buildId=1736:
* `TestIBMQJob.test_custom_job_name` and `TestIBMQJob.test_duplicate_job_name` are failing when asserting over the lengths:
  ```
  >       self.assertEqual(len(job_list), 1)
  E       AssertionError: 0 != 1
  ```
  They are likely a result of the tests attempting to be run against the old API, where we don't support job names - if that is the case, can we revise the tests so they are only executed in the new API?

From https://travis-ci.com/Qiskit/qiskit-ibmq-provider/jobs/224723566:
* one test seems to have failed:
```
ERROR: test_online_qasm_simulator_two_registers (test.ibmq.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
Test online_qasm_simulator_two_registers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Qiskit/qiskit-ibmq-provider/test/decorators.py", line 114, in _wrapper
    return func(obj, *args, **kwargs)
  File "/home/travis/build/Qiskit/qiskit-ibmq-provider/test/decorators.py", line 141, in _wrapper
    return func(*args, **kwargs)
  File "/home/travis/build/Qiskit/qiskit-ibmq-provider/test/ibmq/test_ibmq_qasm_simulator.py", line 101, in test_online_qasm_simulator_two_registers
    result = job.result()
  File "/home/travis/build/Qiskit/qiskit-ibmq-provider/qiskit/providers/ibmq/job/ibmqjob.py", line 255, in result
    'it is {}'.format(str(status)))
qiskit.providers.exceptions.JobError: 'Invalid job state. The job should be DONE but it is JobStatus.ERROR'
```

This one might be a one-timer, but can we double-check?

**Comment by jyu00** [comment]
The first failure was indeed due to using the old api. 

The second was a one-timer. Without an error message or job id it's difficult to determine why it failed. As part of #104 and #176 we should provide more information about why a job failed.
