### ISSUE TITLE
Remove possible race conditions on test_ibmqjob_states.py flow.

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-ibmq-provider#32]
### Informations

- **Qiskit Terra version**: > 0.5
- **Python version**:  > 3.5
- **Operating system**: All supported

### What is the current behavior?
Tests on test_ibmqjob_states are meant to test state flow on jobs. As these jobs have asynchronous behavior, we need a way to avoid possible race conditions. There's some sort of `sleep()` mechanism to sync operations that is not very reliable.

### Steps to reproduce the problem
Race conditions occur very rare, but the way to reproduce them is by launching the tests.

### What is the expected behavior?
Tests should never fail because of race conditions

### Suggested solutions
Haven't thought about it yet.

**Comment by diego-plan9** [comment]
Added to the job refactor project - probably we will be able to close it after the refactor.

**Comment by diego-plan9** [comment]
Closing as the refactor of the job class is now completed, and the issue no longer seems to apply. Thanks @atilag for your patience on this long-standing issue!
