### ISSUE TITLE
Type annotations need to be removed from provider

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#325]
### What is the expected behavior?
In order to have documentation that is uniform over all Qiskit, the type annotations used in the ibmq-provider package, need to be converted into the standard docstring type used in the rest of Qiskit.

**Comment by diego-plan9** [comment]
Can you elaborate on the rationale and the impact in the documentation? Both mechanisms (docstrings and type hinting) ought not to be mutually exclusive, and actually the docstrings are still present and with the same information they contained before the round of type hints.

**Comment by nonhermitian** [comment]
Sure.  The documentation is not consistent when mixing type annotations and conventional docstrings.  For example (since the provider is not in the docs yet https://github.com/Qiskit/qiskit/issues/462):

<img width="740" alt="Screen Shot 2019-09-03 at 6 08 31 AM" src="https://user-images.githubusercontent.com/1249193/64164483-578af080-ce11-11e9-9677-a48532d97bf6.png">

 
you can see that the types of the arguments is in the signature, and not the parameters.  In contrast, for the standard docstrings:

<img width="662" alt="Screen Shot 2019-09-03 at 6 02 47 AM" src="https://user-images.githubusercontent.com/1249193/64164247-db90a880-ce10-11e9-9ebb-f35ab33e1a93.png">

the signature just lists the args, or kwargs, and the types are in the parameters docstring.

In addition, the type annotations can quickly become unwieldy.  For example, The docstring for `execute` would be even harder to read than it is now:

https://qiskit.org/documentation/apidoc/execute.html

However, we really just need to have uniformity over the whole qiskit project, and the docs just highlight this fact.  It is easier to convert the few type annotations that exist into standard docstrings.  However, I have left it up to @ajavadia to decide which format to use.  Either one is fine, but it must be uniform over the whole project.

**Comment by diego-plan9** [comment]
I see! Actually, if you attempt to generate documentation from this package, it should look closer to the second screenshot (with types along the parameters in the bullet list) - as per the mentioned:

> the docstrings are still present and with the same information they contained

If you encounter some members that do not have that information, please submit a PR accordingly! 

All in all, it does seem to be really an issue to be tackled at the generation of the documentation layer: perhaps some tuning of the options used for generating or customization is in order? For example, if using `autodoc`, there are [a number of options to play with](https://www.sphinx-doc.org/es/master/usage/extensions/autodoc.html#confval-autodoc_typehints), such as:


> autodoc_typehints
>
> This value controls how to represents typehints. The setting takes the following values:
> * 'signature' – Show typehints as its signature (default)
> * 'none' – Do not show typehints

Hopefully a similar flexibility or customization can be achieved in the different components used in the doc generation, without needing to sacrifice the bonuses brought by type hinting - closing the issue to avoid confusion while those approaches are explored.

**Comment by nonhermitian** [comment]
So unfortunately your suggestion does not work because then there is no type information available.  In your case, e.g.

https://github.com/Qiskit/qiskit-ibmq-provider/blob/e55be5f306c741e61f97fc1b79819a12d4a8e282/qiskit/providers/ibmq/ibmqbackend.py#L40

you are not using canonical Google style doc strings with annotations.  See for example:

https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

So again, there is an issue with two-different types of docstrings.  Again, will leave to @ajavadia to decide.

**Comment by ismaelfaro** [comment]
Let me coordinate with all of you and @ajavadia this thing.
