### ISSUE TITLE
Proxies seemingly not used in IBMQ v2

### ISSUE THREAD

**Issue by nstamato** [Qiskit/qiskit-ibmq-provider#350]
### Information

- **Qiskit IBMQ Provider version**: 0.3.2
- **API URL or version**: API v2

- **Python version**: 3.6.0
- **Operating system**: Windows

### What is the current behavior?
`IBMQ.load_account()` does not work if you need to use a proxy, even though the proxy is properly specified and stored in the qiskitrc file. 

### Steps to reproduce the problem
Try to use `IBMQ.load_account()` behind a proxy. If you don't need proxies, I guess you could verify that it isn't working by specifying an invalid proxy and trying to connect, it should probably fail by not being able to connect to the proxy.

### What is the expected behavior?
If you specify a proxy to use in qiskitrc, it should use it when calling `IBMQ.load_account()`. This works correctly in v1.

### Suggested solutions
At some point before

https://github.com/Qiskit/qiskit-ibmq-provider/blob/4c86b6734dbe3d7c90790d51d2ca5a038b4d82ae/qiskit/providers/ibmq/api/session.py#L162

`kwargs` needs to be updated to include the proxies, as currently `self.proxies` is not actually used anywhere. I've tried adding

`kwargs.update({'proxies': self.proxies}})`

just before the request is made, but it looks this code is reached a couple of times and (at least) the second time `self.proxies` is empty, and I'm not familiar enough with the end-to-end process to suggest a proper solution.

**Comment by diego-plan9** [comment]
Hi @nstamato ,

can you try comparing the contents of your qiskitrc with the one generated by starting fresh and using the following snippet:

```python
proxies = {
    'urls': {
        'http': 'http://user:password@127.0.0.1:5678',
        'https': 'https://user:password@127.0.0.1:5678'
    }
}
qiskit.IBMQ.save_account('SOME_TOKEN', proxies=proxies)
```

Using that qiskitrc, `load_account()` should be failing due to attempting to use the proxy for all the underlying requests in the session (following up on your suggested solution, some of the connection parameters are stored directly in the `RetrySession`, and passed automatically to all request without needing to be added to the individual `.request()` calls), in a similar way to:

```python
RequestsApiError: "HTTPSConnectionPool(host='auth.quantum-computing.ibm.com', port=443): Max retries exceeded with url: /api/version (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0442d6c0f0>: Failed to establish a new connection: [Errno 111] Connection refused')))"
```

The configuration format for the proxies can be a bit cumbersome - so let's see if we can narrow the problem further!

**Comment by nstamato** [comment]
Hi @diego-plan9,

Indeed if I try what you suggest it fails the way you point out, which is the same as when I pass in the correct parameters.

I think you're right in that the proxies don't need to be added explicitly to the individual `.request()` calls, and I believe I found the source of the issue in the following code:

https://github.com/Qiskit/qiskit-ibmq-provider/blob/4c86b6734dbe3d7c90790d51d2ca5a038b4d82ae/qiskit/providers/ibmq/ibmqfactory.py#L353

This is where it hangs for me, and I think the proxies also need to be passed through the `AuthClient` creation. 

If I do:

```
auth_client = AuthClient(credentials.token,
                                 credentials.base_url, proxies = credentials.proxies['urls'])
```
then it works for me without having to pass the proxies to the `request()` call explicitly.

**Comment by diego-plan9** [comment]
Thanks for the detailed info, @nstamato ! Your diagnosis seems to be spot on - we'll investigate further and issue a fix accordingly.
