### ISSUE TITLE
Revise terra 0.10 compatibility

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#382]
### What is the expected behavior?

With a new release of terra, we should ensure compatibility and prepare things accordingly. With the current terra `master`:
* the provider `0.3.x` _package_ works without changes, although `test_ibmq_job_states.py` fails due to an import that was changed (`new_fake_qobj`) - @luisg5 , can you confirm this is the case?
* the provider `0.4.x` line needs some adjustments, mostly due to marshmallow version updates.

**Comment by luisg5** [comment]
Yeah, `test_ibmq_job_states` fails due to the [import](https://github.com/Qiskit/qiskit-ibmq-provider/blob/46f59e43fb8bf1ed28813b73c780f3a7f395858b/test/ibmq/test_ibmq_job_states.py#L23) Diego mentioned. The issue is that `new_fake_qobj` does not seem to be defined.

**Comment by diego-plan9** [comment]
Closed via #383
