### ISSUE TITLE
JobStatus.ERROR should be a "valid" job state

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-ibmq-provider#390]
### Information

- **Qiskit IBMQ Provider version**: 0.3.3

### What is the current behavior?
When there is an error during the execution, I'm getting the following output:
```
result = job.result()
```
```
**/site-packages/qiskit/providers/ibmq/job/ibmqjob.py in result(self, timeout, wait)
    252         if status is not JobStatus.DONE:
    253             raise JobError('Invalid job state. The job should be DONE but '
--> 254                            'it is {}'.format(str(status)))
    255 
    256         if not self._result:

JobError: 'Invalid job state. The job should be DONE but it is JobStatus.ERROR'
```

### What is the expected behavior?
I would like to see a nicer exception, maybe with `error_message()` and a bit more of an explanation.

### Suggested solutions
Something like:
```
if status is not JobStatus.ERROR:
    raise JobError("The job finished with an error: %s" % job.error_message())
```

**Comment by jyu00** [comment]
With #370 `job.result()` will now raise a `JobError` with the text `Job has failed. Use job.error_message() to get more details.`. 
Some backends give back an error message for each individual experiment, and it'd look messy to try to format that in the `JobError` exception.
