### ISSUE TITLE
Cannot load provider master from terra

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#397]
### Information

- **Qiskit IBMQ Provider version**: master
- **API URL or version**:

- **Python version**: 3.7
- **Operating system**:

### What is the current behavior?

```python
from qiskit.providers.ibmq import IBMQ
```
gives me this:

<img width="1019" alt="Screen Shot 2019-10-16 at 12 51 12 PM" src="https://user-images.githubusercontent.com/1249193/66940912-d465d880-f013-11e9-88a1-816a4f691c4c.png">

**Comment by jyu00** [comment]
This is because the `schemas` package is not included in the build. 

@diego-plan9 are we ready to merge #334? If not we can move `validation.py` out of `schemas`.

**Comment by diego-plan9** [comment]
It seems to have slipped through during #397 - https://github.com/Qiskit/qiskit-ibmq-provider/pull/371#discussion_r331963361

> Can we use a new file, instead of introducing the use .schemas?

So yes, can you move it out of `schemas`?
