### ISSUE TITLE
CHANGELOG and contributing make md not rst 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-ibmq-provider#42]
### Information

- **Qiskit IBMQ Provider version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Since we are not using Sphinx on these in this repo I would make them as to be consistent with the rest of the files in this repo.

**Comment by diego-plan9** [comment]
Just re-checking - Is this issue still current? It seems some of the repositories (for example, terra) still use `.rst` for CHANGELOG and CONTRIBUTING, and I'm not sure if changing it will make it actually less consistent project-wise.

I don't have a strong preference about the format, but for the CHANGELOG at least, I'd lean towards keeping it in .rst, just in case eventually the changelogs make their way to the qiskit.org documentation.

**Comment by diego-plan9** [comment]
Closed via #149
