### ISSUE TITLE
QiskitBackendNotFoundError occurs if I registered both credentials of Q Experience and Q Console

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-ibmq-provider#43]
### Informations

- **Qiskit version**: 0.7.2
- **Python version**: 3.6.8
- **Operating system**: macOS HighSierra

### What is the current behavior?

I have both Q Experience and Q Console accounts and registered them to `IBMQ`. Then, because both systems have a backend with the same name "ibmq_qasm_simulator", `QiskitBackendNotFoundError` occurs.

### Steps to reproduce the problem

```
$ python
>>> from qiskit import IBMQ
>>> IBMQ.load_accounts()
>>> print(IBMQ.backends())
[<IBMQBackend('ibmq_20_tokyo') from IBMQ(xxx, yyy, zzz)>,
 <IBMQBackend('ibmq_qasm_simulator') from IBMQ(xxx, yyy, zzz)>,
 <IBMQBackend('ibmqx4') from IBMQ()>,
 <IBMQBackend('ibmqx2') from IBMQ()>,
 <IBMQBackend('ibmq_16_melbourne') from IBMQ()>,
 <IBMQBackend('ibmq_qasm_simulator') from IBMQ()>]
>>> IBMQ.get_backend('ibmq_qasm_simulator')
QiskitBackendNotFoundError                Traceback (most recent call last)
----> 1 IBMQ.get_backend('ibmq_qasm_simulator')
~/envs/test/lib/python3.6/site-packages/qiskit/providers/baseprovider.py in get_backend(self, name, **kwargs)
     42         backends = self.backends(name, **kwargs)
     43         if len(backends) > 1:
---> 44             raise QiskitBackendNotFoundError('More than one backend matches the criteria')
     45         elif not backends:
     46             raise QiskitBackendNotFoundError('No backend matches the criteria')

QiskitBackendNotFoundError: 'More than one backend matches the criteria'
```

### What is the expected behavior?

Users can choose "ibmq_qasm_simulator" on Q Experience or Q Console.

### Suggested solutions

Change the backend name "ibmq_qasm_simulator" on Q Console.

**Comment by jaygambetta** [comment]
In the qiskit provider tutorial we show how to do this.   Grab by hub or user account.  For quantum experience set hub equal to none.

**Comment by t-imamichi** [comment]
Thanks. I found it. https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/basics/the_ibmq_provider.ipynb

**Comment by t-imamichi** [comment]
I can choose a backend by`IBMQ.get_backend('ibmq_qasm_simulator', hub=None)` or `IBMQ.get_backend('ibmq_qasm_simulator', hub='ibm-q-internal')`.

**Comment by rraymondhp** [comment]
Thanks! I encountered this problem and thanks to this I could solve it!

**Comment by sunn-e** [comment]
I did 
```
qcomp = provider.get_backend('ibm_16_melbourne')
```
I got this error
```
QiskitBackendNotFoundError                Traceback (most recent call last)
<ipython-input-37-21fea2178653> in <module>
----> 1 qcomp = provider.get_backend('ibm_16_melbourne')

~/miniconda2/envs/aims-ml/lib/python3.6/site-packages/qiskit/providers/baseprovider.py in get_backend(self, name, **kwargs)
     44             raise QiskitBackendNotFoundError('More than one backend matches the criteria')
     45         if not backends:
---> 46             raise QiskitBackendNotFoundError('No backend matches the criteria')
     47 
     48         return backends[0]

QiskitBackendNotFoundError: 'No backend matches the criteria'

```

**Comment by jyu00** [comment]
> I did
> 
> ```
> qcomp = provider.get_backend('ibm_16_melbourne')
> ```
> 
> I got this error
> 
> ```
> QiskitBackendNotFoundError                Traceback (most recent call last)
> <ipython-input-37-21fea2178653> in <module>
> ----> 1 qcomp = provider.get_backend('ibm_16_melbourne')
> 
> ~/miniconda2/envs/aims-ml/lib/python3.6/site-packages/qiskit/providers/baseprovider.py in get_backend(self, name, **kwargs)
>      44             raise QiskitBackendNotFoundError('More than one backend matches the criteria')
>      45         if not backends:
> ---> 46             raise QiskitBackendNotFoundError('No backend matches the criteria')
>      47 
>      48         return backends[0]
> 
> QiskitBackendNotFoundError: 'No backend matches the criteria'
> ```

Hi! The name of the backend is `ibmq_16_melbourne ` (you were missing the `q` in `ibmq`).

**Comment by PiyushAuqa** [comment]
I wrote this line (as shown in Qiskit YouTube Channel)
qcomp=provider.get_backend('ibmq_16_melbourne')

and got this one
---------------------------------------------------------------------------
QiskitBackendNotFoundError                Traceback (most recent call last)
<ipython-input-23-527837f581cd> in <module>
----> 1 qcomp=provider.get_backend('ibmq_16_melbourne')

~\anaconda3\lib\site-packages\qiskit\providers\provider.py in get_backend(self, name, **kwargs)
     53             raise QiskitBackendNotFoundError("More than one backend matches the criteria")
     54         if not backends:
---> 55             raise QiskitBackendNotFoundError("No backend matches the criteria")
     56 
     57         return backends[0]

QiskitBackendNotFoundError: 'No backend matches the criteria'


Can anybody help me out here....

**Comment by nonhermitian** [comment]
That device is no longer operational.  You will need to select a different one from those listed here: https://quantum-computing.ibm.com/services?services=systems

**Comment by PiyushAuqa** [comment]
> That device is no longer operational. You will need to select a different one from those listed here: https://quantum-computing.ibm.com/services?services=systems

Thanks man....

**Comment by dmpadulkar** [comment]
IBMQ.load_account()
provider = IBMQ.get_provider('ibm-q')
qdevice = provider.get_backend('ibm_washington')
job = execute(qc, backend= qdevice)
result = job.result()

But got this error

QiskitBackendNotFoundError                Traceback (most recent call last)
<ipython-input-66-023f2de54752> in <module>
      2 
      3 provider = IBMQ.get_provider('ibm-q')
----> 4 qdevice = provider.get_backend('ibm_washington')
      5 job = execute(qc, backend= qdevice)
      6 result = job.result()

~/anaconda3/lib/python3.8/site-packages/qiskit/providers/provider.py in get_backend(self, name, **kwargs)
     53             raise QiskitBackendNotFoundError("More than one backend matches the criteria")
     54         if not backends:
---> 55             raise QiskitBackendNotFoundError("No backend matches the criteria")
     56 
     57         return backends[0]

QiskitBackendNotFoundError: 'No backend matches the criteria'

Help me out

**Comment by rathishcholarajan** [comment]
@dmpadulkar `ibm_washington` is not available on the open access provider. You can try any of the other backends available to you https://quantum-computing.ibm.com/services?services=systems&systems=yours
