### ISSUE TITLE
Revise test_ibmq_backends

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#446]
### What is the expected behavior?
Per the docstring in `test_ibmq_backends`, it's used for "remote backend validation". These tests, however, have low tolerance on data validation and often fail even with good backends. In addition, they are now adapted by the backend team to test new devices, so we probably don't need them in the provider anymore.

**Comment by luisg5** [comment]
Is there anything holding back removing `test_ibmq_backends.py`? Or, is it safe to remove the file?

**Comment by jyu00** [comment]
The backend team doesn't actually use these tests right now because they fail too frequently due to low tolerance on data validation. Before we get rid of them we should update them to make sure they can be used by the backend team.
