### ISSUE TITLE
Test we are specializing the backend class for simulators

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-ibmq-provider#46]
When using a simulator, a special class allowing to call `run` with different parameters is used. We should test we effectively instantiate this class when choosing a simulator.

**Comment by luisg5** [comment]
The IBMQSimulator class contains a run method which handles the different parameters: backend_options and noise_model. 

To test whether the IBMQSimulator class is effectively instantiated, would it be necessary to call the IBMQSimulator run method with the additional parameters. Then, validate that the QObj returned by the IBMQSimulator run method has updated configs?

**Comment by diego-plan9** [comment]
Welcome, @luisg5 !

In this issue, we are only interested in making sure that "the classes that create `IBMQBackend`s and `IBMQSimulator` perform their job as expected" - that is, without really worrying too much about what happens after instantiation (if the objects are of the "right" class, their methods such as `run()` and others will be covered by other tests already in place).

> To test whether the IBMQSimulator class is effectively instantiated ...

... you can just make use of assertions that, once a list of backends is obtained via the regular means, each object that represent a backend is of "the right class" - [`assertIsInstance()`](https://docs.python.org/3.5/library/unittest.html#unittest.TestCase.assertIsInstance) might be helpful in solving the issue.

**Comment by diego-plan9** [comment]
Fixed via #270
