### ISSUE TITLE
`job.result()` needs a refresh option

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-ibmq-provider#466]
it seems like the Job class is caching its result. But it is easy to change the result during post-processing, for example marginalizing over some qubits or doing error mitigation on the result. I think this should not affect the original job result. At least, the job.result() call should have an option to fetch the original result from the API again.

**Comment by jyu00** [comment]
If a user wants to change the result object but keep the original, can't they just do a `copy.deepcopy()`?

**Comment by ajavadia** [comment]
Sure but it will take some time to figure out this is happening (based on my debugging experience). I don’t think it is expected that “job.result()” is *not* returning the result of the executed job every time you call it.

**Comment by jyu00** [comment]
Closed via #469
