### ISSUE TITLE
Can't import Aqua

### ISSUE THREAD

**Issue by ashlesha-p** [Qiskit/qiskit-ibmq-provider#478]
### Information

- **Qiskit IBMQ Provider version**: IBM Q Experience 2.0.0
I am trying to run QSVM but getting an error while importing Aqua. The code was working a few days ago.

<ipython-input-3-4d7d406e0ef5> in <module>
      7 #from datasets import *
      8 from qiskit import Aer
----> 9 from qiskit.aqua.utils import split_dataset_to_data_and_labels, map_label_to_class_name
     10 from qiskit.aqua import run_algorithm, QuantumInstance
     11 from qiskit.aqua.input import ClassificationInput

/opt/conda/lib/python3.7/site-packages/qiskit/aqua/__init__.py in <module>
     27                         register_pluggable,
     28                         deregister_pluggable)
---> 29 from .utils.backend_utils import (get_aer_backend,
     30                                   get_backends_from_provider,
     31                                   get_backend_from_provider,

/opt/conda/lib/python3.7/site-packages/qiskit/aqua/utils/__init__.py in <module>
     22 from .subsystem import get_subsystem_density_matrix, get_subsystems_counts
     23 from .entangler_map import get_entangler_map, validate_entangler_map
---> 24 from .dataset_helper import (get_feature_dimension, get_num_classes,
     25                              split_dataset_to_data_and_labels,
     26                              map_label_to_class_name, reduce_dim_to_via_pca)

/opt/conda/lib/python3.7/site-packages/qiskit/aqua/utils/dataset_helper.py in <module>
     16 
     17 import numpy as np
---> 18 from sklearn.decomposition import PCA
     19 
     20 

/opt/conda/lib/python3.7/site-packages/sklearn/decomposition/__init__.py in <module>
     17 from ._factor_analysis import FactorAnalysis
     18 from ..utils.extmath import randomized_svd
---> 19 from ._online_lda import LatentDirichletAllocation
     20 
     21 __all__ = ['DictionaryLearning',

ImportError: cannot import name 'LatentDirichletAllocation' from 'sklearn.decomposition._online_lda' (/opt/conda/lib/python3.7/site-packages/sklearn/decomposition/_online_lda.cpython-37m-x86_64-linux-gnu.so)

**Comment by jyu00** [comment]
Hi @ashlesha-p! Can you please post your 
1) qiskit version. You can get the versions of all elements by doing `qiskit.__qiskit_version__`
2) scikit-learn version. You can use `pip show scikit-learn`
3) the OS you're using. 

Thanks!

**Comment by ashlesha-p** [comment]
Hi @jyu00 ,

I am using the IBM Q experience Jupyter notebook.

Thanks!

**Comment by jyu00** [comment]
This was an issue with the latest Scikit-Learn. It's now resolved. Thanks for reporting it!

**Comment by MinatiRath** [comment]
@jyu00   ...i am still getting error for qiskit.aqua.input  and run_algorithm

from qiskit.aqua.input import ClassificationInput
from qiskit import Aer
from qiskit.aqua import run_algorithm

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-251ebd9ca2d5> in <module>
----> 1 from qiskit.aqua.input import ClassificationInput
      2 from qiskit import Aer
      3 from qiskit.aqua import run_algorithm

ModuleNotFoundError: No module named 'qiskit.aqua.input'

ImportError                               Traceback (most recent call last)
<ipython-input-9-547e683fbb76> in <module>
      1 import qiskit
----> 2 from qiskit.aqua import run_algorithm

ImportError: cannot import name 'run_algorithm' from 'qiskit.aqua' (/opt/conda/lib/python3.7/site-packages/qiskit/aqua/__init__.py)

**Comment by jyu00** [comment]
Hi @MinatiRath Both `qiskit.aqua.input` and `run_algorithm` were removed in Aqua 0.7 (qiskit meta 0.19). You can read more about the changes in 0.7 [here](https://www.ibm.com/blogs/research/2020/05/new-qiskit-quantum-algorithms-applications/).

**Comment by MinatiRath** [comment]
Thanks jessie.. I figured it out. Can you guide me how I can import my
classical dataset to quantum algorithms.  Currently using datasets provided
by libraries.  Interested to learn more on creating quantum circuits for ML
algorithms.  I would like to record the running time for algorithms on
actual quantum machines.

Thanks once again for your help.

Regards
Minati Rath
