### ISSUE TITLE
the queue is blocked 

### ISSUE THREAD

**Issue by pypdeveloper** [Qiskit/qiskit-ibmq-provider#489]
I am getting an error which says
"Error submitting job: '403 Client Error: Forbidden for url: https://api.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/Jobs?access_token=.... The queue is disabled., Error code: 3245.'"

**Comment by jyu00** [comment]
Hi @pypdeveloper! Which backend were yo using that gave you the error message?

**Comment by jyu00** [comment]
I believe this was due to the backend used was offline for maintenance and switching to a different backend would resolve the issue.
