### ISSUE TITLE
@asyncio.coroutine was deprecated in python 3.8

### ISSUE THREAD

**Issue by iyanmv** [Qiskit/qiskit-ibmq-provider#493]
### Information

- **Qiskit IBMQ Provider version**: 0.4.5
- **API URL or version**: 

- **Python version**: 3.8
- **Operating system**: Archlinux

### What is the current behavior?
Just released new version is supposed to support python 3.8. However, @asyncio.coroutine is used in websockets.py and it has been deprecated in this version, so some warnings are shown to users when importing the module

### Steps to reproduce the problem
With python 3.8, just write `from qiskit import IBQM`

### What is the expected behavior?
Module is imported without warnings

### Suggested solutions
Change `@asyncio.coroutine` to `async def` and `yield from` to `await` as suggested in [Python documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine).

Have a look at this commit: https://github.com/iyanmv/qiskit-ibmq-provider/commit/18aff9685487d69847498d41ad68f128144330b4

This is my first contribution, so I open the issue as suggested in [CONTRIBUTING.md](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/CONTRIBUTING.md) before sending a PR.

**Comment by jyu00** [comment]
hi @iyanmv, thanks for reporting this! We're aware that `coroutine` is deprecated in python 3.8. However, `async def` is not supported in early versions of python 3.5 (which we still support), so switching to `async def` may not be the best solution here. We can, however, suppress the deprecation warning for `coroutine` to make it more user friendly. We'll just need to remember to remove it when we drop python 3.5 support.

**Comment by iyanmv** [comment]
Mmm... true, I totally forgot about python 3.5. Then yes, I think at least suppressing the warning would be nice. Thanks!
