### ISSUE TITLE
job.cancel() returns true but job not cancelled

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#499]
### Information

- **Qiskit IBMQ Provider version**:
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
`job.cancel()` can return `True` even if the cancel had failed.

### Steps to reproduce the problem
It cannot be reproduced at will, but show up in several Travis runs (e.g. [1425](https://travis-ci.com/Qiskit/qiskit-ibmq-provider/jobs/269353015) and [1414](https://travis-ci.com/Qiskit/qiskit-ibmq-provider/jobs/269108014))

### What is the expected behavior?
Job is cancelled if `job.cancel()` returns true.

### Suggested solutions
The provider currently checks for `error` in the response data to determine if the cancel was successful. After talking to the api team, it should also be checking for `'cancelled': True` in the response data.

**Comment by jyu00** [comment]
In some specific window `cancel()` may still fail even with `cancelled: True`.

**Comment by jyu00** [comment]
API rolled out a new release that had a job cancel related fix. This should be re-tested and see if we can close.

**Comment by luisg5** [comment]
When a job was cancelled while in the `RUNNING` state, `cancel()` would succeed. However, after the job finished running, the api would overwrite the `CANCELLED` status to `COMPLETE`. This issue was fixed by their new release, as they do not allow overwriting the job status if it is in a final state (i.e. `CANCELLED`).

**Comment by jyu00** [comment]
As mentioned, `test_skipped_result` failed with 
```
======================================================================
FAIL: test_skipped_result (test.ibmq.test_ibmq_jobmanager.TestResultManager)
Test one of jobs has no result.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jyu00/qiskit-ibmq-provider/test/decorators.py", line 72, in _wrapper
    return func(obj, *args, **kwargs)
  File "/home/travis/build/jyu00/qiskit-ibmq-provider/test/decorators.py", line 100, in _wrapper
    return func(*args, **kwargs)
  File "/home/travis/build/jyu00/qiskit-ibmq-provider/test/ibmq/test_ibmq_jobmanager.py", line 391, in test_skipped_result
    result_manager.get_counts(max_circs)
AssertionError: IBMQManagedResultDataNotAvailable not raised : IBMQManagedResultDataNotAvailable not raised for job 5e6bdf77d9955f0019621576
```

The assert is only called if the `job.cancel()` returned True. However, the status of the job is actually DONE. There isn't much information to go on, but once we have the logging we can look more into this.

**Comment by jyu00** [comment]
Haven't seen this in a while; will re-open if it happens again.
