### ISSUE TITLE
Review `error_message` in case of a total failure.

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit-ibmq-provider#50]
### What is the expected behavior?
PR #48 deals with an error coming from a failed experiment but it could be cases in which the job fails globally. The current implementation does not cover this case. This issue is intended to track this possible corner case.

**Comment by ryan-woo** [comment]
Hi!

Backend is currently not schema compliant. Currently, you'll get a "KeyError" if an error occurs on the backend. We're fixing it.

`error_message()` (namely `IBMQConnector._get_job()`) should still check that the job it received is indeed schema compliant, so this is still an issue.

**Comment by diego-plan9** [comment]
Closed by #126 - @ryan-woo , hopefully it includes a safeguard against jobs not being fully conformant to the schema: please reopen if you find the problem still persists for the cases you mention.
