### ISSUE TITLE
Graceful handling of API downtime

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#504]
### What is the expected behavior?

A new mechanism will be introduced in the API for providing clear information about the API being down (for maintenance, etc, with more accurate information for the users on when it will be available). The provider should be able to understand this new mechanism and pass the information onto the users - will probably be able to take advantage of the PRs related to #419 with some extra tuning.

**Comment by jyu00** [comment]
server maintenance message will look like 
```
{
  "error": {
    "statusCode": 521,
    "name": "MAINTENANCE",
    "message": "Planned maintenance from 01/27/2020 06:00 EST to 01/27/2020 08:00 EST",
    "code": 0
  }
}
```
error code is TBD

**Comment by jyu00** [comment]
Error code is 1999.
