### ISSUE TITLE
Nicer string format for QueueInfo

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#509]
### What is the expected behavior?
It'd be nice if the user can do `print(job.queue_info())` and see formatted queue info data, something like
```
position: foo
status: bar
...
```
so they don't have to format individual fields.

**Comment by luisg5** [comment]
How does the following format seem?
```
Job Info:
    position: 499
    status: PENDING_IN_QUEUE
Estimated Time Info:
    start time: 2020-01-14 21:07:48.179000+00:00
    complete time: 2020-01-14 21:08:19.579000+00:00
Priority Info:
    hub: 1.0
    group: 1.0
    project: 1.0
```
Of course, with perhaps some date formatting as well...

**Comment by jyu00** [comment]
How about a simpler format, like
```
Job 12345 queue information:
  queue position: 499
  status: job is queued
  estimated start time: in 1 hour
  estimated completion time: in 2 hours
  hub priority: 1.0
  group priority: 1.0
  project priority: 1.0
```

I like the more informative date formatting that iqx website has (e.g. give relative instead of absolute time).  

Given the complexity of the output, I think we should add a new method to `QueueInfo` (maybe `format()`) instead of changing `__str__` like I had originally planned. So a user would do `print(job.queue_info().format()`).
