### ISSUE TITLE
Handling of malformed proxy configuration

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#528]
### What is the expected behavior?

On a run with a newer version of Python, four of the proxy tests were failing with:
```
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme
```

```
test/ibmq/test_proxies.py::TestProxies::test_invalid_proxy_address_authclient FAILED
test/ibmq/test_proxies.py::TestProxies::test_invalid_proxy_address_versionclient FAILED
test/ibmq/test_proxies.py::TestProxies::test_invalid_proxy_port_authclient FAILED
test/ibmq/test_proxies.py::TestProxies::test_invalid_proxy_port_versionclient FAILED
````

It seems related to the way `INVALID_PORT_PROXIES` and `INVALID_ADDRESS_PROXIES` are defined (ie. lacking a `http://` prefix in the value), and due to recent changes In Python (more details at https://github.com/psf/requests/issues/5297).

It might be just a matter of tweaking the tests and keeping track of the upstream issue - however, it might be possible that users who had previously a working-but-now-invalid proxy configuration encounter the same issue, which is a bit obscure to track. Perhaps adding an extra check on our side or a similar measure might be in order?

**Comment by jyu00** [comment]
Thanks @diego-plan9 for discovering this! 
In addition to fixing the tests, we should probably check/convert the proxy address, especially since it's also broken in python 3.8.1.
