### ISSUE TITLE
Avoid deprecation warnings coming from terra

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#53]
### What is the expected behavior?

The test suite currently emits several deprecation warnings, mostly due to the use of `qiskit.compile()`, which is to be deprecated in 0.9. We should move the tests to use the new transpilation workflow accordingly.

**Comment by jwoehr** [comment]
Is this mostly a case of replacing phrases like:

test_ibmq_connector.py:        `qobj = compile(self.qc1, backend=backend, seed=self.seed, shots=1)`

with appropriate calls to `qiskit.transpiler.transpile()` using appropriate arguments?

**Comment by diego-plan9** [comment]
Yes - it should be a matter of running the tests, capturing the deprecation warnings (most test runners will be able to provide a list of them, usually at the end of the output or during the tests), and tracing down which line of the test is causing the deprecation warnings.

I'd indeed expect that most of them would be due to `compile()` - for those, it would mean replacing those lines with calls to the appropiate non-deprecated function (usually the warnings themselves provide recommendation on how to adapt to the new behaviour, but might involve digging a bit into terra and being up to date with the recent `master` changes).

**Comment by jwoehr** [comment]
I am not quite clear on how the test harness works to run the tests. What should I explore, please?

**Comment by jwoehr** [comment]
(I am thinking about both this issue and #52 )

**Comment by jwoehr** [comment]
Yes, separate PRs. Will explore Makefiles for more insight and tackle both #52 and #53 though possibly not this week yet.

**Comment by jwoehr** [comment]
Working on this one.

Attributes have changed. In the case of kwargs like `shots=` I have noted them and dropped them from the argument list when switching from `compile()` to `transpile`.

There are other attributes I haven't quite figured out what to do about. Here are two examples of the errors:

```

**Comment by jwoehr** [comment]
Here's another attrib `as_dict`

```
======================================================================
ERROR: test_api_run_job_fail_backend (test.ibmq.test_ibmq_connector.TestIBMQConnector)
Test running a job against an invalid backend.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/test/decorators.py", line 178, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/home/jax/work/QISKit/DEV/qiskit-ibmq-provider/test/ibmq/test_ibmq_connector.py", line 85, in test_api_run_job_fail_backend
    self.assertRaises(BadBackendError, api.run_job, qobj.as_dict(),
AttributeError: 'QuantumCircuit' object has no attribute 'as_dict'

======================================================================
ERROR: test_get_job_includes (test.ibmq.test_ibmq_connector.TestIBMQConnector)
Check the field includes parameter for get_job.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jax/work/QISKit/DEV/qiskit-terra/qiskit/test/decorators.py", line 178, in _wrapper
    return decorated_func(self, *args, **kwargs)
  File "/home/jax/work/QISKit/DEV/qiskit-ibmq-provider/test/ibmq/test_ibmq_connector.py", line 150, in test_get_job_includes
    job = api.run_job(qobj.as_dict(), backend_name)
AttributeError: 'list' object has no attribute 'as_dict'
```

**Comment by diego-plan9** [comment]
Thanks!

```
    shots = qobj.config.shots
```
note that depending on how you obtained that `qobj`, it might indeed be a `list` (as the last error mentions) - not only the arguments have changed, but also the return types might have "changed" (for example, `transpile()` might return a list of circuits, that you need to pass to `assemble()` in order to get the actual qobj).

**Comment by jwoehr** [comment]
You mean I'm actually going to have to think?! No fair! :) Thanks for the help, @diego-plan9 , I'll continue to work on this.
