### ISSUE TITLE
Rename IBMQ* to IBM*

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#530]
### What is the expected behavior?
In order to differentiate between the IBM Quantum Experience cloud platform and the services offered by IBM Quantum, the main API class in Qiskit will be renamed from `IBMQ*` to `IBM*`. The `IBMQ` variable will still be supported until a future release. 

Similarly, the following will be renamed:
IBMQFactory -> IBMAccount
IBMQBackendService -> IBMBackendService
AccountProvider -> IBMProvider

**Comment by rathishcholarajan** [comment]
Tracked here https://github.com/Qiskit-Partners/qiskit-ibm/issues/22
