### ISSUE TITLE
Default Provider saved in account

### ISSUE THREAD

**Issue by ryan-woo** [Qiskit/qiskit-ibmq-provider#545]
### What is the expected behavior?

It would be wonderful to be able to set your default provider in the IBMQ account that gets saved to disk. Then `IBMQ.load_account()` returns your default provider.

**Comment by nonhermitian** [comment]
I concur. This is simply adding a new key to the `[ibmq]` section, however the logic around it will require some work, e.g. what to do if the set default is no longer there.
