### ISSUE TITLE
Remove marshmallow 

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#553]
### What is the expected behavior?
`qiskit-terra` is moving away from marshmallow due to performance. The provider will need to stop using terra's marshmallow schemas as well as removing its own, since it relies on terra's methods and for consistency. 

This needs to be in sync with https://github.com/Qiskit/qiskit-terra/pull/3383 which removes schemas like `QobjSchema` used by the provider.

Tasks:
- [x] Remove marshmallow from ibmq-provider
- [x] Custom encoder to convert objects to JSON serializable
- [x] Custom decoder to convert
    - [x] list back to complex
    - [x] string back to datetime 
- [x] Test cases to verify en/decoder

**Comment by mtreinish** [comment]
I started this in: https://github.com/Qiskit/qiskit-ibmq-provider/pull/555

**Comment by jyu00** [comment]
One thing to note is that for complex numbers, marshmallow used to convert them from list to complex when a `from_dict()` is done. This now needs to be done in the provider when it deserializes the data from the server.
