### ISSUE TITLE
Error map fails for ibmq_armonk

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#557]
### Information

- **Qiskit IBMQ Provider version**: master
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
Using Jupyter widget to display `ibmq_armonk` information raises an exception:
```
qiskit/providers/ibmq/visualization/interactive/error_map.py in iplot_error_map(backend, figsize, show_title, remove_badcal_edges, background_color, as_widget)
    339 
    340     # CX error rate colorbar
--> 341     min_cx_err = min(cx_errors)
    342     max_cx_err = max(cx_errors)
    343     if cmap:

UnboundLocalError: local variable 'cx_errors' referenced before assignment
```

### Steps to reproduce the problem
Run the following code in a notebook:
```
from qiskit import IBMQ
import qiskit.providers.ibmq.jupyter
provider = IBMQ.load_account()
backend = provider.get_backend('ibmq_armonk')
backend
```

### What is the expected behavior?
The call should not fail.

### Suggested solutions
In `error_map.py`, always initialize `cx_errors` (as it's good practice) and create `min_cx_err` and `max_cx_err` only if there is a coupling map. The heat map will also need some work for the single qubit device.

**Comment by nonhermitian** [comment]
Huh,  thought I fixed that. Will do.
