### ISSUE TITLE
Rethink qiskit integration

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#561]
### What is the expected behavior?
As we add more and more features to the IQX account, e.g. visualizations, dashboards, etc., it quickly becomes apparent that the current namespace packaging is not the best.  For example, grabbing a visualization requires the user to do:

```
from qiskit.providers.ibmq.visualization import blah
```

So anything is three sub-modules down from the main qiskit namespace, where as it is in reality only one level down from the IQX account main level.

The suggestion here is not to be injected into qiskit providers, but rather be a standalone module, e.g. `iqx_account`.  Then

```
from iqx_account.visualization import blah
```

**Comment by jyu00** [comment]
Are you suggesting we move the whole `qiskit.providers.ibmq` to a separate `iqx_account` package? How about Aer provider?

**Comment by nonhermitian** [comment]
Yes I am suggesting this.  `Aer` is a bit different in that it does not have an account and provides only a single service, simulators in this case.  The IQX is a more rich than that.  We have devices, simulators, additional services, and now local routines for visualization and the like.  Not to mention all the additional account related functionality.  Also, it is not a provider anymore in the language we use today.

**Comment by jyu00** [comment]
And it will no longer be part of the `qiskit` meta package?

**Comment by nonhermitian** [comment]
I am thinking if this is the way to go.

**Comment by rathishcholarajan** [comment]
Tracked here https://github.com/Qiskit-Partners/qiskit-ibm/issues/22
