### ISSUE TITLE
IBMQJobManager.retrieve_job() fails when a job has crashed or has been cancelled 

### ISSUE THREAD

**Issue by danielbultrini** [Qiskit/qiskit-ibmq-provider#569]
[errordump.txt](https://github.com/Qiskit/qiskit-ibmq-provider/files/4261563/errordump.txt)

### Information

- **Qiskit IBMQ Provider version**:0.5.0
- **API URL or version**:https://api-qcon.quantum-computing.ibm.com/api/

- **Python version**:3.7.4
- **Operating system**:Ubuntu

### What is the current behavior?
Cancelled/Crashed job in a IBMQJobManager().retrieve_job_set() instance does not allow you to retrieve any of the jobs that did complete successfully. 

### Steps to reproduce the problem
Give any list of circuits that spans a number of jobs to IBMQJobManager(), some of these jobs will be forever stuck in a 'Creating' phase (in my case, four days), so if it is cancelled (but this has happened to me if a job happened to crash for whatever reason) and you try to retrieve the job manager instance, it will fail to retrieve the useful successful runs. 

### What is the expected behavior?
That it will return everything it can and an empty result object (or warning) for the missing data rather than crashing. 

### Suggested solutions
Make it so that it returns the successful jobs alongside some warning that a job failed, perhaps returning a NaN filled Result object that can be skipped in the analysis phase.

**Comment by jyu00** [comment]
Hi @danielbultrini , can you please provide the code that caused `retrieve_job()` to fail? 

I tried to recreate the scenario but it worked for me:

```
>>> jm = IBMQJobManager()
>>> job_set = jm.run(circs, backend=backend)
>>> while JobStatus.INITIALIZING in job_set.statuses():   # wait for jobs to be submitted before canceling
...     time.sleep(1)
>>> job_set.jobs()[1].cancel()
>>> print(job_set.report(detailed=False))
Job set name: 2020-02-27T22:29:10.279232
          ID: 4670459bf2e7422aaf7d8cd7cac6d2ef-15828425502793012
        tags: []
Summary report:
       Total jobs: 2
  Successful jobs: 0
      Failed jobs: 0
   Cancelled jobs: 1
     Running jobs: 0
     Pending jobs: 1
>>> rjob_set = IBMQJobManager().retrieve_job_set(job_set_id=job_set.job_set_id(), provider=provider)
>>> result = rjob_set.results()
./qiskit/providers/ibmq/managed/managedjob.py:164: UserWarning: Unable to retrieve job result for experiments 2-2, job ID=5e5842b7c8c7bc0018166b5f: 'Unable to retrieve job result. Job was cancelled.' 
  self.start_index, self.end_index, self.job.job_id(), err))
>>> result.get_counts(1)
{'00': 460, '01': 57, '10': 38, '11': 469}
>>> rjob_set.jobs()[0].status()
<JobStatus.DONE: 'job has successfully run'>
>>> rjob_set.jobs()[1].status()
<JobStatus.CANCELLED: 'job has been cancelled'>
```

**Comment by danielbultrini** [comment]
So, after assigning some circuits and qubits I sent the job like you (but without the while loop)

`circuits = transpile(circuits,backend=backend,optimization_level=1,basis_gates=['u1', 'u2', 'u3', 'cx', 'id'],initial_layout=[3,4,5,6])
job_name = 'meridians_poughkeepsie_qbit_4_8000'
jm = IBMQJobManager()
job_set=jm.run(circuits,backend=backend,name=job_name,max_experiments_per_job=240,shots=8192)
ID = job_set.job_set_id()
file_obj = open('../results/'+job_name+'.txt','a')
file_obj.write(ID)
file_obj.close()
`
And I let this run. Now,  something that is different is that one of the jobs was stuck in 'Creating' for multiple days, so I cancelled it (seeing as the job manager was stuck in an infinite loop when I tried to return the files). Then I tried to read back the job by reading the ID, as such:

`file_obj = open('../results/'+job_name+'.txt','r')
ID = fileobj.readline()
jm_Set = IBMQJobManager().retrive_job_set(ID, provider=provider)
`

And then I got that error. That being said, I fortunately had not closed the python instance running on my server, and I was able to retrieve all the jobs , including the cancelled ones somehow.

**Comment by jyu00** [comment]
Hi @danielbultrini , can you give me more information on where/what error occurred? Specifically

> (seeing as the job manager was stuck in an infinite loop when I tried to return the files).

Which statement was stuck in an infinite loop? Was it `job_set.results()`?

> jm_Set = IBMQJobManager().retrive_job_set(ID, provider=provider) `
> And then I got that error. 

Do you remember what error it was?

Lastly, do you know if the job that got stuck in `CREATING` and later cancelled was truly cancelled (i.e. its status showed `CANCELLED`)?

**Comment by jyu00** [comment]
Closing since the issue is stale. Will reopen if this happens again.
