### ISSUE TITLE
need to silence warnings about old format jobs in `backend.jobs()`

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-ibmq-provider#57]
### What is the expected behavior?
I consistently get a warning when using `backend.jobs()` for jobs in the old format.

```
/anaconda3/lib/python3.6/site-packages/qiskit/providers/ibmq/ibmqbackend.py:188: DeprecationWarning: Some jobs are in a no-longer supported format. Please send the job using Qiskit 0.8+. Old jobs:
 - 5c1569e0d463c70054fb1753
```

What is the utility of this warning? There isn't any way to actually resubmit that job, because one cannot even get a handle to old jobs (`backend.retrieve_job()` raises an error for old jobs).

```
IBMQBackendError: 'Failed to get job "5c1569e0d463c70054fb1753": job in pre-qobj format'
```

So one is stuck with some old format jobs in the database that always raise warnings. 

I think we should silence the warning (the error makes sense, because at that point we are explicitly saying we want that particular job).

**Comment by diego-plan9** [comment]
I believe the warning was introduced mostly so the user can "see" all their jobs (as in, `.jobs()` would return a list of valid `Job`, plus the warning for those jobs that are no longer valid) - without it, `5c1569e0d463c70054fb1753` would not be "displayed" by terra or the IBMQ provider at all.

This said, I agree it can be a tad inconvenient, and it is an use case that seems a bit exotic - probably users transitioning from relatively old versions of terra (0.6) would be affected, and technically they can get the ids from the frontend. Would removing the warning and adding a note in the docstring about pre-qobj jobs be a good compromise?

**Comment by ajavadia** [comment]
Yes that would be great.
