### ISSUE TITLE
nest_asyncio.apply() fails when not running under main thread

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#595]
### Information

- **Qiskit IBMQ Provider version**:
- **API URL or version**:

- **Python version**:
- **Operating system**:

### What is the current behavior?
`nest_asyncio.apply()` fails with `no current event loop in thread` when `websocket.py` is imported on a child thread. 

### Steps to reproduce the problem
Run a script that imports qiskit on a child thread:

```
import threading

def import_fun():
    import qiskit

t = threading.Thread(target=import_fun)
t.start()
t.join()
```

### What is the expected behavior?
One should be able to import `qiskit-ibmq-provider` on a child thread. 

### Suggested solutions
Manually get the event loop before calling `nest_asyncio.apply()`. If one is not available, create a new loop.

**Comment by czachow** [comment]
I will try to solve this issue
