### ISSUE TITLE
Couldn't connect to IBMQ server: error during login: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kanakk** [Qiskit/qiskit-ibmq-provider#597]
### Information

- **Qiskit IBMQ Provider version**: 0.7.2
- **Python version**: Python 3.6.8 :: Anaconda, Inc.
- **Operating system**: Ubuntu 16.04 LTS

### What is the current behavior?

from qiskit import IBMQ
provider = IBMQ.save_account('TOKEN API')
provider = IBMQ.load_accounts()

### What is the expected behavior?
I wish to generate random number using qiskit quantum computer on my local machine using python API

Error :
"Couldn't connect to IBMQ server: error during login: Expecting value: line 1 column 1 (char 0)"

Please help.

**Comment by kanakk** [comment]
![image](https://user-images.githubusercontent.com/35399739/77223924-f5b08f00-6b86-11ea-8682-191dedecf0a3.png)

**Comment by jyu00** [comment]
hi @kanakk, this error is due to bad data received from the server, and it usually works after a retry. Issue #531 was open to address this, and it should be fixed soon.

**Comment by jyu00** [comment]
This was fixed on the server side.
