### ISSUE TITLE
Current stable branch fails with qiskit terra 0.7.1

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-ibmq-provider#60]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

It assumes `qiskit.exceptions` which exists on the current master, but 0.7.1 did not have it.
This requires a fix on the stable branch.

**Comment by ajavadia** [comment]
OK @mtreinish helped me understand what's going on. I think the issue then is that the new qiskit_ibmq_provider release must have qiskit_terra 0.8 as a dependency.

**Comment by diego-plan9** [comment]
Yes, it is by design - I'll remove the `bug` label an leave the issue open as a reminder of the work left to be done when the new release is up (basically, uncomment the line about `qiskit-terra>=0.8` dependency, and update meta-qiskit).

**Comment by diego-plan9** [comment]
0.1 has just been released :tada:
