### ISSUE TITLE
Bad Request API resultDownloadUrl: Cannot get presigned download url

### ISSUE THREAD

**Issue by desireevl** [Qiskit/qiskit-ibmq-provider#617]
### Information

- **Qiskit IBMQ Provider version**: 0.17.0 (Python)
- **API URL or version**: ```https://api.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/Jobs/<job number>/resultDownloadUrl```

- **Python version**: 3.6
- **Operating system**: Ubuntu Linux

### What is the current behavior?
```qiskit.providers.ibmq.job.exceptions.IBMQJobApiError: "Unable to retrieve result for job <job number>: '400 Client Error: Bad Request for url: https://api.quantum-computing.ibm.com/api/Network/ibm-q/Groups/open/Projects/main/Jobs/<job number>/resultDownloadUrl. Cannot get presigned download url., Error code: 3202```

### Steps to reproduce the problem
The issue only occurs when running on a real device (not a simulator). Code has worked fine in the past (prior to version 0.17.0 being released).
Running code from [here](https://github.com/desireevl/quantum-game-theory/blob/master/backend/logic.py):

```
IBMQ.load_account()
provider = IBMQ.get_provider(hub='ibm-q')
small_devices = provider.backends(filters=lambda x: x.configuration().n_qubits == 5 and not x.configuration().simulator)
least_busy_device = least_busy(small_devices)
job_sim = execute(self._quantum_game.circ, least_busy_device, shots=n_times)
res_sim = job_sim.result()
counts = res_sim.get_counts(self._quantum_game.circ)
```

The error occurs after execute() and before .result()
### What is the expected behavior?
Circuit to execute fully and results of run become available.

**Comment by bennyboer** [comment]
Downgrading to qiskit `0.16.2` or `0.16.1` did not help for me either.

**Comment by vaho670** [comment]
I have got the 3202 error with the simulator too.
I have tried this : 
`result = job.result(10.0, 10.0, True, True)
 try:
        counts = result.get_counts("failed_experiment")
 except QiskitError:
        print("Experiment failed!")
        print(job.error_message())`
and the **error_message()** is _None_

**Comment by nonhermitian** [comment]
This is being fixed as we speak.

**Comment by jyu00** [comment]
This problem is due to erroneous response sent by the server through the websocket connection, which is used by `job.result()` to wait for the job to finish. As a **temporary** workaround, you can manually poll for the job status, bypassing websocket:
``` 
import time
from qiskit.providers.jobstatus import JOB_FINAL_STATES

while job.status() not in JOB_FINAL_STATES:
    time.sleep(5)
result = job.result()
```

"Temporary" is highlighted because using `job.status()` to poll is generally not recommended as it could cause the server to deny your request due to excessive requests.

**Comment by jyu00** [comment]
This is now fixed. Thanks @desireevl for reporting it!
