### ISSUE TITLE
new copyright header required

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#67]
### What is the expected behavior?
The following copyright statement must replace the old one in all the files:

```python

# This code is part of Qiskit.
#
# (C) Copyright IBM 2019.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
```

**Comment by nonhermitian** [comment]
@diego-plan9, can this be done asap?

**Comment by diego-plan9** [comment]
Sure, will be up before the release.

In the meantime, can you elaborate on the specific format to be used for the copyright year? Some of the files in this repo have `2017` or `2018`, as they were part of `qiskit-terra` prior to the repository split. In those cases, should the original year be preserved, or instead replaced by `2019` blindly?

**Comment by nonhermitian** [comment]
Ok, yes I  see the issue.  The files previously in terra should be `2017, XXXX` where `XXXX` is the year that particular file was added.  For others, it would be `2018, XXXX` since this repo was started in 2018.  Of course if the files have `XXXX` equal to the year 2018 or 2017, then the `XXXX` can be omitted.

Many thanks

**Comment by diego-plan9** [comment]
Sounds sensible enough - thanks, will ping you back when it's up (aiming at tomorrow)!

**Comment by diego-plan9** [comment]
@nonhermitian the PR is up at #75 - can you review?
