### ISSUE TITLE
When will ibmq_5_yorktown - ibmqx2 be available again?

### ISSUE THREAD

**Issue by SergioUnoxx** [Qiskit/qiskit-ibmq-provider#709]
I see in https://quantum-computing.ibm.com/ that the ibmqx2 backend is in the "online: dedicated use" status.  When will it be available for use again? I was using that backend for my Masters' Degree Thesis and suddenly I couldn't use it anymore .

**Comment by jyu00** [comment]
According to [this announcement](https://qiskit.slack.com/archives/C8GLMQ1U5/p1594644452243400) from 2 days ago, the current estimate is another 8 days before `ibmq_yorktown` (`ibmqx2`) and `ibmq_melbourne` come back (yorktown maybe a little less, melbourne maybe a little more). New updates will be posted in the Slack channel, but I'll keep this issue open for people who don't have/want to use Slack.

**Comment by SergioUnoxx** [comment]
I consider myself one of that people. Thank you very much for the info!

**Comment by jyu00** [comment]
@SergioUnoxx quick update, `ibmq_melbourne` is still down, but `ibmqx2` is now available!

**Comment by jyu00** [comment]
`ibmq_16_melbourne` is also back. Closing the issue.
