### ISSUE TITLE
job.cancel() throws TypeError

### ISSUE THREAD

**Issue by mstypulk** [Qiskit/qiskit-ibmq-provider#71]
### Informations

- **Qiskit version**: 0.1 (ibmq-provider)
- **Python version**: 3.7.2
- **Operating system**: macOS

### What is the current behavior?
When calling job.cancel() on a job that has not yet finished, you get the following error:
`TypeError: cancel_job() takes 2 positional arguments but 5 were given`

### Steps to reproduce the problem
Create any circuit. Transpile and assemble circuits. Run the job on any IBMQ backend, and call job.cancel() before it completes. You get this error and the job will run until it fails or successfully completes.

### What is the expected behavior?
The job is cancelled and job.status() shows that the job was cancelled.

### Suggested solutions
It looks like the error is being thrown because of the call to `cancel_job()` inside of `job.cancel()`. Inside of `job.cancel()` hub, group, and project are stored but never used. After looking through past commits it looks like these variables we used as input when calling `cancel_job()`, but that is no longer the case. I would guess that removing them from the `cancel_job()` call would fix the issue.

**Comment by diego-plan9** [comment]
Thanks, @mstypulk - will include a fix in the upcoming release (for tracking, slightly related to #69 ).
