### ISSUE TITLE
Consider supporting local simulator in job manager

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#715]
### What is the expected behavior?
A followup to #711. 

Some users initially run their experiments on local simulators and migrate to real devices once they're satisfied with the code (since real devices are much slower). It'd be nice if they can use job manager in both environments.

**Comment by AustinGilliam** [comment]
Actually came here to suggest this - glad it is being discussed. I spend about 80% of my time on the simulator, and spend the last 20% switching back and forth between the real devices and the simulator (debugging, trying different parameters, etc.). This would make the latter half of my workflow easier to manage.
