### ISSUE TITLE
Hello, Im getting an SSL certificate error (screen shot below). Any ideas on how to fix it appreciated. Thanks

### ISSUE THREAD

**Issue by jayur** [Qiskit/qiskit-ibmq-provider#724]
Hello, Im getting an SSL certificate error (screen shot below). Any ideas on how to fix it appreciated. Thanks
![sslerror](https://user-images.githubusercontent.com/21326124/88491621-ec7e6700-cf58-11ea-9ed7-c2b0882ba917.png)

_Originally posted by @jayur in https://github.com/Qiskit/qiskit-ibmq-provider/issues/122#issuecomment-664051213_

**Comment by jyu00** [comment]
Hi @jayur, it's likely related to how CA certificates are setup on your local machine. You can try upgrading `certifi` (`pip install --upgrade certifi`).

**Comment by jayur** [comment]
Hi Jessie

Thanks for your suggestion - I tried this but I am still getting this error. Is it something to do with trusted websites? I have to use the following command for pip install:
pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade certifi

**Comment by jyu00** [comment]
If you had to add `--trusted-host` that means pip could not verify the host - another indicator that it's related to your CA certificate setup. If you're behind a proxy, you may need to add the proxy CA certification to the bundle Python uses. If you're behind a firewall, check if your firewall requires a proxy to connect to outside websites. 

Another thing to try is to verify your Python environment (sometimes they get messed up for whatever reason). You can start a new virtual environment, and/or verify the location shown in `pip show certifi` is actually listed in your python path (`sys.path`).

**Comment by jyu00** [comment]
It was reported this has been fixed. Closing.
