### ISSUE TITLE
IQXJsonEncoder -- serialization of datetime element

### ISSUE THREAD

**Issue by ehchen** [Qiskit/qiskit-ibmq-provider#729]
### Information
![image](https://user-images.githubusercontent.com/1069980/89089554-bb37d980-d352-11ea-9484-170e503ddaa4.png)

### What is the current behavior?

When saving a datetime element, included by default, there is a serialization error when using the IQXJsonEncoder.

### Steps to reproduce the problem

`mydict2 = {'a':'b','date':datetime.datetime(2020,7,30,12,33,56)}
DIR = './data/notebook/'
file_path = DIR + 'foo2.json'
print(file_path)
with open(file_path, 'w') as fp:
    json.dump(mydict2, fp, cls=IQXJsonEconder)`

error:

`./data/notebook/foo2.json

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-a3617d0bd440> in <module>
      6 print(file_path)
      7 with open(file_path, 'w') as fp:
----> 8     json.dump(mydict2, fp, cls=IQXJsonEconder)
      9 #     json.dump(mydict2, fp, cls=json.encoder.JSONEncoder)

~/opt/anaconda3/envs/qiskit_v0/lib/python3.8/json/__init__.py in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    177     # could accelerate with writelines in some versions of Python, at
    178     # a debuggability cost
--> 179     for chunk in iterable:
    180         fp.write(chunk)
    181 

~/opt/anaconda3/envs/qiskit_v0/lib/python3.8/json/encoder.py in _iterencode(o, _current_indent_level)
    429             yield from _iterencode_list(o, _current_indent_level)
    430         elif isinstance(o, dict):
--> 431             yield from _iterencode_dict(o, _current_indent_level)
    432         else:
    433             if markers is not None:

~/opt/anaconda3/envs/qiskit_v0/lib/python3.8/json/encoder.py in _iterencode_dict(dct, _current_indent_level)
    403                 else:
    404                     chunks = _iterencode(value, _current_indent_level)
--> 405                 yield from chunks
    406         if newline_indent is not None:
    407             _current_indent_level -= 1

~/opt/anaconda3/envs/qiskit_v0/lib/python3.8/json/encoder.py in _iterencode(o, _current_indent_level)
    436                     raise ValueError("Circular reference detected")
    437                 markers[markerid] = o
--> 438             o = _default(o)
    439             yield from _iterencode(o, _current_indent_level)
    440             if markers is not None:

~/opt/anaconda3/envs/qiskit_v0/lib/python3.8/site-packages/qiskit/providers/ibmq/utils/json_encoder.py in default(self, o)
     35         if isinstance(o, ParameterExpression):
     36             return float(o)
---> 37         return json.JSONEncoder.default(self, o)

~/opt/anaconda3/envs/qiskit_v0/lib/python3.8/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type datetime is not JSON serializable`

### What is the expected behavior?

The JsonEncoder should be able to serialize this data..

### Suggested solutions

Not sure.. is there a bug in datetime, or the construction of the IQXJsonEncoder? Is it perhaps a python incompatibility issue? @jyu00 @mtreinish

**Comment by jyu00** [comment]
`datetime` objects are not JSON serializable. `IQXJsonEconder` is only meant to encode `Qobj`, which does not include `datetime`.

**Comment by ehchen** [comment]
It seems like the backend.properties returns datetime.datetime() in the following format, which may mean I have to subclass the JsonEncoder to handle these instances:

For example, backend = provider.get_backend(device), backend.properties returns:
`last_update_date=datetime.datetime(2020, 8, 2, 10, 7, 8, tzinfo=tzutc())`

https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable/36142844#36142844

**Comment by jyu00** [comment]
`backend.properties` does have `datetime`, but, as indicated by its docstring, `IQXJsonEncoder` is only for `Qobj` (i.e. [QasmQobj](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qobj/qasm_qobj.py#L384) or [PulseQobj](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qobj/pulse_qobj.py#L512)), not for other objects in `qiskit`. 

There are many ways of converting backend properties into a JSON, if that's what you're trying to achieve. You can manually convert each `datetime` to a string, or subclass `JSONEncoder` to convert all `datetime`, or use the `default=str` trick mentioned in your link (although it may convert more than just `datetime`).

**Comment by jyu00** [comment]
Closing. Let me know if you have more questions.
