### ISSUE TITLE
Addition of a deletion feature in the IBMQ circuit composer

### ISSUE THREAD

**Issue by tgag17** [Qiskit/qiskit-ibmq-provider#749]
### What is the expected behavior?
There should be a bin icon/delete gate option to remove a gate that has been put by mistake

**Comment by jyu00** [comment]
@tgag17 If you're referring to the IBM Quantum Experience Circuit Composer, you can already delete a gate by clicking on the gate you want to delete, then on the little `x` that pops up:

![image](https://user-images.githubusercontent.com/28284230/91754288-26b1d880-eb97-11ea-924e-c9c6504056dc.png)

And just for future reference, please open suggestions/bug reports related to Circuit Composer on the IBM Quantum Experience website: https://quantum-computing.ibm.com/support. The Circuit Composer is not part of qiskit-ibmq-provider.
