### ISSUE TITLE
Attach user id as job attribute for easier job search, related to issue #745.

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-ibmq-provider#751]
### What is the expected behavior?
In the same vein as issue #745, I'd like to propose adding an IBMid or a user id of some sort as an attribute of a job result, such that you can use your user id to retrieve a list of your jobs on a certain backend. For people that don't have an IBMid, I'm not sure how we would identify a person sending jobs, but it would have to be unique to that user, and act the same way as an IBMid. It could be an email address or a username, just a way to identify that person. I'm very open to comments and critiques on this, I just think this might making retrieving jobs more convenient.

**Comment by jyu00** [comment]
> such that you can use your user id to retrieve a list of your jobs on a certain backend.

You can already do that by using `backend.jobs()`. It will only return your own jobs.

**Comment by wmurphy-collabstar** [comment]
Oh okay, thank you very much. I will close this issue then.
