### ISSUE TITLE
Add quantum_volume attribute to BackendConfiguration

### ISSUE THREAD

**Issue by edwinagnew** [Qiskit/qiskit-ibmq-provider#759]
Get the quantum volume of a backend. You can currently do this for number of qubits: 
```
import IBMQ
provider = IBMQ.get_provider(hub='ibm-q')
provider.backends()[3].configuration().num_qubits # = 5
```
And so add a feature to also enable:

`provider.backends()[3].configuration().quantum_volume # = 16 `

Is there anywhere this can be found currently apart from the IBMQ website?

**Comment by jyu00** [comment]
You can actually do `backend.configuration().quantum_volume` already, for backends that do have quantum volumes (i.e. not `ibmq_qasm_simulator`). It's not documented, but that's being worked on (see #747).
