### ISSUE TITLE
Cannot load IBMQ account

### ISSUE THREAD

**Issue by andywangyzfh** [Qiskit/qiskit-ibmq-provider#769]
### Information

- **Qiskit IBMQ Provider version**: 0.9.0
- **API URL or version**: Qiskit 0.21.0

- **Python version**: Python 3.8
- **Operating system**: MacOS 10.15.7

### What is the current behavior?
Failed to connect to IBMQ in Ipython and jupyter notebook. When I tried to connect to IBMQ as I used to, this HTTPError was shown.
```python3
HTTPError                                 Traceback (most recent call last)
~/Library/Python/3.8/lib/python/site-packages/qiskit/providers/ibmq/api/session.py in request(self, method, url, bare, **kwargs)
    272             response = super().request(method, final_url, **kwargs)
--> 273             response.raise_for_status()
    274         except RequestException as ex:

/usr/local/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 

HTTPError: 403 Client Error: Forbidden for url: https://api.quantum-computing.ibm.com/api/Network/devices/ibmqx2/bookings/v2?initialDate=2020-09-30T16%3A48%3A42.263920%2B00%3A00&endDate=2020-09-30T17%3A48%3A42.263920%2B00%3A00
```
I was able to have access IBMQ several weeks ago, but now the access is forbidden. I tried to load the same account in the online IBM Quantum Lab and it was successful. Is this a bug?

### Steps to reproduce the problem
Load IBMQ account in jupyter notebook.

### What is the expected behavior?
Successfully connect to IBMQ.

### Suggested solutions
N/A

**Comment by jyu00** [comment]
@andywangyzfh Can you post your code that encountered this issue?

**Comment by andywangyzfh** [comment]
@jyu00 Here is my code.
```python3
import numpy as np
import math
import matplotlib.pyplot as plt
from IPython.display import display
import cmath
from sympy import symbols, solve
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, \
    BasicAer, execute, IBMQ, __qiskit_version__
from qiskit.tools.visualization import plot_histogram
import qiskit

IBMQ.save_account('<MY_API_TOKEN>', overwrite=True)
# Load account
IBMQ.load_account()
provider = IBMQ.get_provider('ibm-q')

# Find the least busy device to use
from qiskit.providers.ibmq import least_busy
possible_devices = provider.backends(filters=lambda x: x.configuration().n_qubits >= num_qubits and x.configuration().simulator == False)
qcomp = least_busy(possible_devices)
print("Found: ", qcomp) 
```

**Comment by jyu00** [comment]
Hi @andywangyzfh , thank you for sharing the code! The exception is raised by this line
```
qcomp = least_busy(possible_devices)
```
which now checks whether there is a reservation coming up for the backend. 

However, I don't know why you're getting the `Forbidden for url` error, as public users should have access to the url. If you don't mind sharing with me the email address on your IBMQ account (you can email it me at jessieyu@us.ibm.com), I can ask one of the IBMQ admins to look into this.

In the meantime, you can bypass the error by skipping reservation checking:
```
qcomp = least_busy(possible_devices, reservation_lookahead=None)
```

**Comment by jyu00** [comment]
Closing as it's stale. Feel free to re-open if you encounter this issue again.
