### ISSUE TITLE
IBMQJob.queue_info issue

### ISSUE THREAD

**Issue by PIQ-BDTech-ENSEA** [Qiskit/qiskit-ibmq-provider#770]
### Information

- **Qiskit IBMQ Provider version**: 0.9.0
- **API URL or version**: Qiskit 0.21.0

- **Python version**: 3.8
- **Operating system**: Microsoft Windows 10 Famille  10.0.18362

### What is the current behavior?
queue_info() always return a None object.

`AttributeError: 'NoneType' object has no attribute 'estimated_complete_time'
`
### Steps to reproduce the problem

```
from qiskit import IBMQ, assemble, transpile, QuantumCircuit, execute, Aer
from qiskit.circuit.random import random_circuit
import numpy as np
from qiskit.visualization import plot_histogram

provider = IBMQ.load_account()
backend = provider.backends.ibmq_vigo
circuit = QuantumCircuit(2, 2)
circuit.h(0)
circuit.cx(0, 1)
circuit.measure([0,1], [0,1])
qobj = assemble(transpile(circuit, backend=backend), backend=backend)
job = backend.run(qobj)
Queue_info = job.queue_info()
print(Queue_info.estimated_complete_time)

```

### What is the expected behavior?

Successfully return the estimated_complete_time for the job and Queue_info is not a NoneType object.

### Suggested solutions

N/A

**Comment by jyu00** [comment]
Hi @PIQ-BDTech-ENSEA, job queue info is not immediately available when a job is submitted. It is calculated _after_ the job is queued, so after initializing/validating phases. It is also not available if the job is already running. As documented, `queue_info()` returns a `None` if the data is unavailable.

Having said that, I could update the docstring to make it clearer that it's only available soon after a job is queued.

**Comment by PIQ-BDTech-ENSEA** [comment]
Hi @jyu00 thanks for your quick answer.  I will take all this into account in the rest of my development.
