### ISSUE TITLE
Handle list API response body changes

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibmq-provider#782]
## Information

- **Qiskit IBMQ Provider version**: 0.10.0
- **Python version**: n/a
- **Operating system**: n/a

### What is the current behavior?

The newly added support for experiments with the resultsdb endpoint in IQX are going to need to handle a response payload change for the following APIs:

- GET /devices
- GET /device_components
- GET /experiments
- GET /analysis_results

The response body on those today is an array but they are going to change to an object with a field that contains the array, e.g.:

```json
[]
```

becomes

```json
{
    "experiments": []
}
```

The field in the response body object is the same as the path resource, so `devices`, `device_components`, `experiments` and `analysis_results`.

### Suggested solutions

From a client perspective there are two ways to handle this really:

1. Proactive: add some compatibility code now to handle the two different forms of responses and then remove the compatibility code at some later date. This could be backported to the 0.10.x series.
2. Reactive: just change and release a new version once the server changes. Note that Travis CI will likely be blocked until this is fixed after the server changes (we could coordinate when the server side change happens if that helps).

**Comment by jyu00** [comment]
Since the service is still in beta I probably won't try to maintain backward compatibility. We will need some kind of versioning policy when compatibility is needed.

**Comment by mriedem** [comment]
For handling `GET /devices` would it be something like just changing this https://github.com/Qiskit/qiskit-ibmq-provider/blob/0.11.0/qiskit/providers/ibmq/api/rest/root.py#L192 to be:

```python
raw_data = self.session.get(url).json()['devices']
```

? Or would you leave those alone so the root REST API code returns the full response body and lower level code handles parsing the response body like here:

https://github.com/Qiskit/qiskit-ibmq-provider/blob/0.11.0/qiskit/providers/ibmq/experiment/experimentservice.py#L98

so that would be come:

```python
return self._api_client.experiment_devices()['devices']
```

Just wondering if you want some help with this.
