### ISSUE TITLE
Let IBMQJobManager.run() also take one circuit instead of just a list of circuits.

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-ibmq-provider#786]
### What is the expected behavior?
The expected behavior is that you can run one circuit with IBMQJobManager.run() instead of having to run a list of circuits. For example, if you want to run only one circuit with IBMQJobManager.run() method, then with the enhancement you don't need to put the circuit variable in brackets to make it a list.

**Comment by jyu00** [comment]
Closed by #857.
