### ISSUE TITLE
backend.reservations returns reservations irrespective of the backend.provider

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#792]
### Information

- **Qiskit IBMQ Provider version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Calling `backend.reservations()` returns all the reservations, regardless of what provider the reservations are made for.  Therefore one might be confused that they can use that `backend` instance to execute in the reservation block.

### What is the expected behavior?
`backend.reservations()` should return reservations for the provider from which the backend is instantiated.

**Comment by jyu00** [comment]
This is intentional, and the idea is to allow people to get an idea about which backends to avoid. For example, if a backend has a shorter queue but has an upcoming reservation in an hour, and I know my job won't finish before then, I'd know to pick a different backends.

There is a plan to add a `my_reservations()` method that returns only reservations for the provider, but that hasn't been implemented yet.

**Comment by nonhermitian** [comment]
But you don't know which backend instance actually allows you to take advantage of the reservation because they all report the same info. This makes it difficult to use without going to the IQX to look up the provider.

**Comment by jyu00** [comment]
My point is that instead of changing `backend.reservation()` to _only_ return reservations you can use, there should be a new method (or a new keyword) that does just that. So users can know which backends to avoid and which backends to take advantage of. I opened #799 to track the new feature.

**Comment by nonhermitian** [comment]
Closing since not a bug.

**Comment by nonhermitian** [comment]
I will add though that the doc string should probably be modified to make it clear what is being returned here.  I am also not sure why `mode` is not returned if not the owner of the reservation?  Indeed, a different user could still execute if a backend is in priority mode, but not dedicated.  So if the goal is to inform people, the mode would help in this regard.
