### ISSUE TITLE
Reservation mode returns None

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibmq-provider#795]
### Information

- **Qiskit IBMQ Provider version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Doing `reservation.mode` returns `None`.  In the cases tested, the IQX correctly says they are dedicated mode.  Since all reservations are booked with a "mode", this field should not be empty.

```python
print(res)
print(res.mode)

<BackendReservation(backend_name=ibmq_casablanca, start_datetime=2020-10-27T01:00:00-04:00, end_datetime=2020-10-27T04:00:00-04:00, duration=180, reservation_id=5f9237b6390ef20013653113)>
None
```

**Comment by nonhermitian** [comment]
I think, after reading the `backend.reservations()` doc strings that this may just be my error when querying reservations that I do not own.  Thus closing since it is the intended behavior.

**Comment by jyu00** [comment]
It is the intended behavior, but if IQX dashboard is showing the reservation mode, I don't see why we can't. It'd give users more information on whether to avoid the backend (e.g. dedicated mode) or to take the risk (e.g. priority mode).

**Comment by nonhermitian** [comment]
Ok, but the IQX only shows your reservations (your providers), not those of others.  That is the difference that I thought made it ok to close.
