### ISSUE TITLE
Error detected using the qiskit.providers.ibmq.job.ibmqjob.wait_for_final_state() in a python multiprocess context

### ISSUE THREAD

**Issue by aaita92** [Qiskit/qiskit-ibmq-provider#803]
### Information

- **Qiskit IBMQ Provider version**: 0.20.1
- **Python version**: 3.7.9
- **Operating system**: Mac OS 10.15.6

Issue opened together with @eleonorapeck

### What is the current behavior?

during the execution of the qiskit.providers.ibmq.job.ibmqjob.wait_for_final_state() function on a python multiprocess context I retrieve the following error:

`
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<string>", line 1, in <module>
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 837, 
in wait_for_final_state
    self._wait_for_completion(timeout=timeout, status_queue=status_queue)
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/site-packages/qiskit/providers/ibmq/job/ibmqjob.py", line 874, in _wait_for_completion
    self.job_id(), timeout=timeout, wait=wait, status_queue=status_queue)
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/site-packages/qiskit/providers/ibmq/api/clients/account.py", line 362, in job_final_status
    job_id=job_id, timeout=timeout, status_queue=status_queue)
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/site-packages/qiskit/providers/ibmq/api/clients/account.py", line 414, in _job_final_status_websocket
    self.client_ws.get_job_status(job_id, timeout=timeout, status_queue=status_queue))
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/site-packages/nest_asyncio.py", line 90, in run_until_complete
    self._run_once()
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/site-packages/nest_asyncio.py", line 116, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/utente/opt/miniconda3/envs/test_be2_deployment/lib/python3.7/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor
`

**Comment by eleonorapeck** [comment]
Following the issue

**Comment by jyu00** [comment]
This is a limitation on MacOS related to Python multiprocessing. That is, you cannot create an event loop prior to a fork and use it in the child process. For example, 
```
def _async_wait(job):
    job.wait_for_final_state()

with futures.ProcessPoolExecutor() as executor:
    job = execute(circuis, backend)
    future = executor.submit(_async_wait, job)
result = future.result()
```
In the code above, an event loop is created with the main program, and `wait_for_final_state()` attempts to use that loop (to communicate with the server) in a child process created by `executor.submit()`.  If you use a new loop in the child process, e.g. 
```
def _async_wait(job):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    job.wait_for_final_state()
```
then the `Bad file descriptor` error will go away.

HOWEVER, the code still wouldn't work because `ProcessPoolExecutor` pickles the objects, in this case including `qiskit.providers.ibmq.api.session.RetrySession`, for the child process. `RetrySession` inherits from an upstream package `requests`, which defines its own `__getstate__` that doesn't include `RetrySession`'s variables. 

I can make `RetrySession` pickleable if that's what you need, but keep in mind Python multi-processing doesn't work very well on MacOS, especially 10.15.

**Comment by eleonorapeck** [comment]
Thank you @jyu00 for you answer!
I tried to execute the multiprocess Python enabling the account for each process with the apikey. When the job is in DONE state I am able to get the results, but when I use wait_for_final_state I get the following error:
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)`
Did it ever occur to you?
Thanks

**Comment by jyu00** [comment]
If you haven't already, you need to run `/Applications/Python 3.7/Install Certificates.command` to replace the root certificate (the REAME in the directory has a bit more information).

**Comment by eleonorapeck** [comment]
Sorry @jyu00 I didn't mention that after your suggestion we started doing test on Cloud Foundry in order to get rid of the Mac OS problem with Python's multiprocess, so the error I get in the last message is in a CF environment.
Thank you again for your help!

**Comment by jyu00** [comment]
The error message is saying that the CA certificate is not in the trust store, so it's related to the configuration of your environment. I'm not super familiar with Cloud Foundry, but this page: https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python has more information on how Python does SSL communication.
