### ISSUE TITLE
backend.run() should take a list of circuits

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#808]
### What is the expected enhancement?
Allow `backend.run()` to take a list of circuits instead of Qobj

**Comment by born-2learn** [comment]
Can I give this a try, @jyu00?

**Comment by jyu00** [comment]
@born-2learn I appreciate the offer, but I already finished writing the code :). Perhaps you can take a look #786 if you're looking for something to work.

**Comment by born-2learn** [comment]
@jyu00 Sure, I can work on #786
