### ISSUE TITLE
RequestApiErrror when loading IBMQ account

### ISSUE THREAD

**Issue by ajrazander** [Qiskit/qiskit-ibmq-provider#835]
### Information

- **Qiskit IBMQ Provider version**:  0.11.1
- **Python version**: 3.7.7
- **Operating system**: Mac OS 10.15.7

### What is the current behavior?
When I run `IBMQ.load_account()` I get an HTTPError:
`HTTPError: 401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken
The above exception was the direct cause of the following exception:`

that is caused by a RequestApiError:

`RequestsApiError: '401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. Login with IBM ID required., Error code: 3445.'`

### Steps to reproduce the problem
I have refreshed my API token, used `IBMQ.save_account('MY_REFRESHED_TOKEN', overwrite=True)`. I also tried using `IBMQ.delete_account()` then refreshing my API token and saving it--no luck. Same error every time. I don't even know what IBM ID refers to.

### What is the expected behavior?
I expect `IBMQ.load_account()` to load my account, so I can access IBM's Casablanca quantum computer for the open science prize.

### Suggested solutions
I have tried all solutions I could think of which is why I am now reporting here for help.

**Comment by jyu00** [comment]
IBM Q Network users need to log in using their IBM ID. This was a change made a while ago. Presumably you don't have an IBM ID account if you don't know what that is, so you'll need to:

1. Go to the IBM Quantum Experience (IQX) website. Log out if you're already logged in.
2. At the bottom left of the homepage where it says "New to IBM Quantum Experience? Create an IBMid account.", click on "Create an IBMid account"
3. Follow the instructions to create an IBM ID account. Be sure to use the same email you used to sign into IQX so it finds the same account.
4. Once finished, sign into IQX using your new IBM ID account
5. This may or may not change your API token. If it does, use `IBMQ.save_account(NEW_TOKEN)` to save your new token locally.

**Comment by ajrazander** [comment]
This worked! Thank you!
