### ISSUE TITLE
Remove the warning message when loading IBMQ account.

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-ibmq-provider#849]
### What is the expected enhancement?
At the moment, when you run the command IBMQ.load_account(), the following warning message appears: 
opt/conda/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqfactory.py:192: UserWarning: Timestamps in IBMQ backend properties, jobs, and job results are all now in local time instead of UTC.
  warnings.warn('Timestamps in IBMQ backend properties, jobs, and job results '

Even though it is not an error and doesn't affect the rest of the code at all, I think it misleads people into thinking something is wrong. My idea is to remove that warning, and if people are curious about what time zone is used for recording information about jobs, then they can inquire about it with a command. I'm not sure what that command would look like, but I'm happy helping with it wherever I can.

**Comment by nonhermitian** [comment]
This was solved in #841.

**Comment by wmurphy-collabstar** [comment]
Okay great, I'll close this then.
