### ISSUE TITLE
IBMQJobFailureError should not refer to user-space variables

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-ibmq-provider#850]
The following exception suggested to get more details by running `job. error_message`:  
https://github.com/Qiskit/qiskit-ibmq-provider/blob/a23af9354f06ae4a1a96c452821feb179b6638ff/qiskit/providers/ibmq/job/ibmqjob.py#L283

However, the variable `job` existence depends on the user environment, if they set the `IBMQJob` instance as `job`. In general, I don't think is a good idea to refer to a variable that might or not exist as a way to help the user. In this case in particular, I think the `error_message` should just be included in this message and avoid the inderection. 
```
error_message = ": %s" % self.error_message()
```

**Comment by jyu00** [comment]
The error message is already included in the exception, _unless_ it has multiple lines (Aer gives 1 line per experiment). Multi-line messages don't format well in the exception, and the message could be very long - hence it asks the user to do `job.error_message()`. 

I agree that using `job.` is not the best strategy. However, the more common `IBMQJob.error_message()` would be even more confusing as many don't know what `IBMQJob` is. Perhaps I'll just remove the `job.` part and say just `error_message()` (although I suspect users who don't have a lot of programming experience still wouldn't know what to do with it).
