### ISSUE TITLE
Use websockets for proxies

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#869]
### What is the expected enhancement?
`job.result()` today uses polling instead of websockets if proxies are involved because the `websockets` client ibmq-provider uses doesn't support proxies. There might be other clients we can use that do support proxies.

**Comment by renier** [comment]
might be an option to use websocket-client https://stackoverflow.com/a/47509073

**Comment by jyu00** [comment]
yeah I looked at `websocke-client` a while ago. Since it's a completely different package, the ibmq-provider websocket path will need to be rewritten and retested, so it won't be a quick and easy fix.
