### ISSUE TITLE
Fails to access IBMQ

### ISSUE THREAD

**Issue by weiT1993** [Qiskit/qiskit-ibmq-provider#903]
### Information

- **Qiskit IBMQ Provider version**: 0.12.1
- **Python version**: 3.8.5
- **Operating system**: Linux

### What is the current behavior?
Fails to access providers.

### Steps to reproduce the problem
```
from qiskit import IBMQ
IBMQ.save_account('MY_API_TOKEN',overwrite=True)
provider = IBMQ.get_provider(hub='ibm-q', group='open', project='main')
```
raises `No provider matches the specified criteria`.

### What is the expected behavior?
My IBMQ account UI indicates that I do have access to the provider. It should return me the provider. I have been using this to access the provider with no issues since very recently.

### Suggested solutions
Helps check IBMQ access backend?

**Comment by jyu00** [comment]
hello @weiT1993, you need to load the account before getting the provider. `save_account()` only saves the account but doesn't load it. For example:

```
from qiskit import IBMQ
IBMQ.save_account('MY_API_TOKEN',overwrite=True)  # This only needs to be done once, unless your token changes
IBMQ.load_account()
provider = IBMQ.get_provider(hub='ibm-q', group='open', project='main')
```

By the way, `load_account()` returns the default open provider. So you can essentially do `provider = IBMQ.load_account()`

**Comment by weiT1993** [comment]
Thanks for the response. `IBMQ.load_account()` returns `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://auth.quantum-computing.ibm.com/api/version` error.

**Comment by jyu00** [comment]
It's possible that the file used to save the credentials is somehow corrupted. Can you try deleting and re-saving the token:
```
from qiskit import IBMQ
IBMQ.delete_account()
IBMQ.save_account('MY_API_TOKEN')
provider = IBMQ.load_account()
```

If that still doesn't work, then it's likely your account was disabled, and you'll need to contact IBMQ support for that. On the https://quantum-computing.ibm.com/ website, the upper right corner has a question mark. You  can click on it, select Feedback, and then change the topic to "Report a bug or issue".

**Comment by weiT1993** [comment]
Yes I am getting the same error. I left a report via the website. It's weird because the web UI shows up everything as normal.

**Comment by weiT1993** [comment]
Closing this issue because the problem was that Cloudflare (the company hosting the site name) blocked our NAT IP address. It has been unblocked.
