### ISSUE TITLE
Add runtime jobs and programs to IQX dashboard

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#951]
### What is the expected enhancement?
The "IQX dashboard" Jupyter widget current shows the progress of a circuit job. 

![image](https://user-images.githubusercontent.com/28284230/121069147-27694200-c79b-11eb-9909-2da73b46795c.png)

It should be updated to also show runtime jobs and programs (name and description). In addition, the widget should be renamed to something like "IBM Quantum dashboard" as the name IQX (IBM Quantum Experience) is no longer used.

[This tutorial](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/docs/tutorials/2_jupyter_tools.ipynb) shows how to use the Jupyter widgets, and the code is in the `jupyter` directory.

**Comment by rathishcholarajan** [comment]
Issue moved to [Qiskit-Partners/qiskit-ibm #83](https://github.com/Qiskit-Partners/qiskit-ibm/issues/83) via [**ZenHub**](https://www.zenhub.com/)
