### ISSUE TITLE
Add experiment service options

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#958]
### What is the expected enhancement?
In preparation for the qiskit-experiments release, we need an `option()` method in `ExperimentService` that allows users to set service options. Currently the only option would be `auto_save`.  This setting will be persisted in `qiskitrc`, which currently contains only credential information.

A user should be able to do

```
provider.experiment.set_options(auto_save=True)  # use this option in the session and save to disk
provider.experiment.option('auto_save')  # return specified option
provider.experiment.options()  # return all saved options
```

**Comment by rathishcholarajan** [comment]
Fixed by https://github.com/Qiskit/qiskit-ibmq-provider/pull/1032
