### ISSUE TITLE
Enable proxy support for new API

### ISSUE THREAD

**Issue by diego-plan9** [Qiskit/qiskit-ibmq-provider#97]
### What is the expected behavior?

As part of the transition, support for the proxy configuration keys needs to be adjusted for the new API v2 - the basics are in place for the `Session`, but it needs to be enabled fully. Ideally, we should also include some tests for the feature, probably with the help of some lightweight proxy server in the CI.

On the wishlist, testing support for NTLM proxies would be high on the list - although it might not be technically feasible.

**Comment by diego-plan9** [comment]
Fixed by #119

**Comment by yunfan** [comment]
do you support socks5 proxy?
