### ISSUE TITLE
Interpret Runtime's 'Cancelled - Ran too long' state as Cancelled.

### ISSUE THREAD

**Issue by renier** [Qiskit/qiskit-ibmq-provider#972]
Interpret Runtime's 'Cancelled - Ran too long' state as Cancelled.

Docs will be updated soon to reflect this new state in the API. This is a workaround until the cancelled state has a reason value (implies state becomes a tuple of status, reason).

**Comment by jyu00** [comment]
This perhaps would be better mapped to `Error` instead of `Cancelled`, since the latter implies it's cancelled by the user. We should also have a new `error_message()` method to tell the user _why_ it failed.
