### ISSUE TITLE
Retrieve historical data for backend.defaults()

### ISSUE THREAD

**Issue by knsmith** [Qiskit/qiskit-ibmq-provider#978]
Past calibration property data is available with 

`backend.properties(datetime=datetime)`

but past

`backend.defaults()`

are not available. This would be convenient to recover a `instruction_schedule_map` from a different calibration cycle.

**Comment by rathishcholarajan** [comment]
Issue moved to [Qiskit-Partners/qiskit-ibm #77](https://github.com/Qiskit-Partners/qiskit-ibm/issues/77) via [**ZenHub**](https://www.zenhub.com/)
