### ISSUE TITLE
Remove ibmq_16_melbourne from tutorial

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#987]
### Information

- **Qiskit IBMQ Provider version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The tutorial uses `ibmq_16_melbourne` which has since been retired. The tutorial needs to be updated.

**Comment by rathishcholarajan** [comment]
Have to remove the retired `ibmq_athens` as well from the results in the tutorials.
