### ISSUE TITLE
test_upload_update_plot_data failing since July 9

### ISSUE THREAD

**Issue by mriedem** [Qiskit/qiskit-ibmq-provider#992]
### Information

- **Qiskit IBMQ Provider version**: master (git cloned July 9)
- **Python version**: 3.8.1
- **Operating system**:  Ubuntu Bionic

### What is the current behavior?

This is a CI system that runs with the following variables set:

```
$ export USE_STAGING_CREDENTIALS=True
$ export QE_STAGING_URL=https://auth-dev.quantum-computing.ibm.com/api
$ export QE_STAGING_HGP=ibm-q-internal/labgroup/mriedem
```

This test started failing:

```
======================================================================

FAIL: test_upload_update_plot_data (test.ibmq.test_experiment.TestExperiment)

Test uploading and updating plot data.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/IBM-Q-Software/sw-ibmq-results/qiskit-ibmq-provider-master/test/ibmq/test_experiment.py", line 694, in test_upload_update_plot_data

    self.assertEqual(rplot, friend_bytes, "Retrieved plot not equal updated plot.")

AssertionError: b'hello world' != b'hello friend!' : Retrieved plot not equal updated plot.
```

### Steps to reproduce the problem

Presumably just run the qiskit-ibmq-provider experiment tests.

### What is the expected behavior?

Tests should pass CI.

### Suggested solutions

I'm not sure what's causing the failure, there don't appear to be any related changes specific to the experiment service on July 9.

**Comment by mriedem** [comment]
> I'm not sure what's causing the failure, there don't appear to be any related changes specific to the experiment service on July 9.

Hmm, this might be due to a change that went into the `staging` environment that this is testing against on July 9:

https://github.ibm.com/IBM-Q-Software/sw-ibmq-results/blob/staging/docs/release-notes.md#0349

Looking at the test: https://github.com/Qiskit/qiskit-ibmq-provider/blob/98f4f6e17072eeedd087c4030f4128c5e983c2c6/test/ibmq/test_experiment.py#L672

Yeah so the problem is the test creates a plot, then updates it with different content and as soon as it updates the plot it retrieves it to compare against the original plot expecting them to be different but they are the same because the actual plot content update is happening asynchronously in the background (plots are stored in cloud object storage now which is slower than just putting them in a database).

There isn't currently a way to really tell from the client when the plot is fully uploaded in the backend so I'm not sure what we should do about this test for now. It could poll and timeout after 5 seconds but that's not awesome. We could add a request header to allow the client to tell the server it wants to do a synchronous upload?

**Comment by jyu00** [comment]
This to me is a server side issue. If I upload a plot, I expect to be able to retrieve it immediately. Or at least be notified that it's still pending and have a way to know when it's done.

**Comment by mriedem** [comment]
> 
> 
> This to me is a server side issue. If I upload a plot, I expect to be able to retrieve it immediately. Or at least be notified that it's still pending and have a way to know when it's done.

That's fair. I think we will add a request header on the server side to allow the client to say if they want the upload to happen synchronously and if so they'll get a 200 response back whereas now (in `staging`) they are getting a 202 back and the plot upload happens asynchronously.

I'm going to leave this issue open since we'll need to make a change to Qiskit (the code in general or just the test specifically) to tell the server to do the plot upload synchronously.

**Comment by mriedem** [comment]
I've got a fix locally, running the test it passes:

```
$ LOG_LEVEL=DEBUG python -m unittest -v test.ibmq.test_experiment.TestExperiment.test_upload_update_plot_data
session._log_request_info:DEBUG:2021-07-13 11:16:37,909: Endpoint: /experiments. Method: GET. 
session._log_request_info:DEBUG:2021-07-13 11:16:38,524: Endpoint: /device_components. Method: GET. 
test_upload_update_plot_data (test.ibmq.test_experiment.TestExperiment)
Test uploading and updating plot data. ... session._log_request_info:DEBUG:2021-07-13 11:16:38,741: Endpoint: /experiments. Method: POST. 
session._log_request_info:DEBUG:2021-07-13 11:16:39,209: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730/plots. Method: POST. 
session._log_request_info:DEBUG:2021-07-13 11:16:39,475: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730. Method: GET. 
session._log_request_info:DEBUG:2021-07-13 11:16:39,738: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730/plots. Method: POST. 
session._log_request_info:DEBUG:2021-07-13 11:16:39,950: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730. Method: GET. 
session._log_request_info:DEBUG:2021-07-13 11:16:40,168: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730/plots/batman.svg. Method: PUT. 
session._log_request_info:DEBUG:2021-07-13 11:16:40,928: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730/plots/batman.svg. Method: GET. 
session._log_request_info:DEBUG:2021-07-13 11:16:41,947: Endpoint: /experiments/f99fd545-1070-4899-a68a-37c499bf0730. Method: DELETE. 
ok

----------------------------------------------------------------------
Ran 1 test in 9.502s

OK
```

Checking the server logs for that PUT request it's correctly uploading the plot synchronously - I can tell because the response code is 200 rather than 202:

>Jul 13 10:16:40 resultsdb-55d6c5f86d-8bvxc resultsdb 30 {"name":"app-server","hostname":"resultsdb-55d6c5f86d-8bvxc","pid":21,"level":30,"method":"PUT","url":"/experiments/f99fd545-1070-4899-a68a-37c499bf0730/plots/batman.svg","status_code":200,"content_length_bytes":31,"response_time_ms":511,"host":"api-dev.quantum-computing.ibm.com","user_agent":"python-requests/2.25.1","remote_addr":"96.42.89.247","msg":"","time":"2021-07-13T15:16:40.914Z","v":0}
