### ISSUE TITLE
Accommodate and parse JSON schema as runtime program metadata

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibmq-provider#996]
### What is the expected enhancement?
Today Qiskit Runtime server takes plain text for parameter/return value metadata for a Qiskit Runtime program. Something that looks like:

```
  "parameters": [
    {"name": "iterations", "description": "Number of iterations to run. Each iteration generates and runs a random circuit.", "type": "int", "required": true}
  ],
```

For `parameters`, `return_values`, and `interim_results`, the server plans to switch to accepting JSON schemas instead. So the `parameters` above would look something like

```
    "parameters": {
      "type": "object",
      "properties": {
        "iterations": {
          "type": "integer",
          "description": "Number of iterations to run. Each iteration generates and runs a random circuit.",
        }
      },
      "required": [
        "iterations"
      ]
    }
  },
```

To prepare for this change we'll need to 
1) allow a user to specify JSON schema instead of plain text when uploading a program
2) parse JSON schema to construct `RuntimeProgram` objects. JSON schema can be complicated with nested `$ref` etc, but we can start with some small. [This repo](https://github.com/coveooss/json-schema-for-humans) can serve as a reference.

**Comment by rathishcholarajan** [comment]
Copied to https://github.com/Qiskit-Partners/qiskit-ibm/issues/44
